"""Claude Code: the three hooks in `settings.json`, the status line we compose with, and
the `/tycho-*` slash commands."""

from __future__ import annotations

import json
from pathlib import Path

from ...read import harness as harness_mod
from ...store import state
from .configfile import (
    _current_text,
    _prune,
    _drop_backup,
    _groups_of,
    _hooks_of,
    _load,
    _status,
    _strip_claude_tycho,
    _write,
    _write_text,
)
from .spelling import (
    GLOBAL,
    REPO,
    _command_for,
    _command_for_scope,
    _is_tycho_status,
    claude_dir,
    settings_path,
    status_command,
)


# HTML comment so it renders invisibly when previewed as Markdown.
_SLASH_MARKER = "<!-- Generated by tycho init. -->"

# "We declined to touch this file" — the CLI matches on this constant for its exit code.


# Milliseconds. A user who sets their own value keeps it.
_STATUS_REFRESH_MS = 1000


def _install_claude(repo: Path, scope: str = REPO) -> str:
    """Claude gets the hooks and (if free) the status bar, in **one** write: a second write
    would back up our own first one and destroy the `.bak` the user would restore. `scope`
    picks the tree and nothing else — a global install differs only in the command (guarded,
    see `_GLOBAL_GUARD`), in leaving an existing user statusLine alone, and in recording no
    per-repo install state."""
    # .claude/settings.json → hooks.Stop is a list of matcher-groups, each with a `hooks` list.
    path = settings_path(repo, scope)
    data = _load(path)
    command = _command_for_scope("hook", scope)
    hooks = _hooks_of(data, path)
    groups, existed = _strip_claude_tycho(_groups_of(hooks, "Stop", path))
    groups.append({"hooks": [{"type": "command", "command": command}]})
    hooks["Stop"] = groups
    # SessionStart: surface a newer-version notice to the user at agent bootup.
    ss_command = _command_for_scope("session-start", scope)
    ss_groups, ss_existed = _strip_claude_tycho(_groups_of(hooks, "SessionStart", path))
    ss_groups.append({"hooks": [{"type": "command", "command": ss_command}]})
    hooks["SessionStart"] = ss_groups
    # Mark a run in flight at prompt time, so the badge shows "verifying" for the whole turn
    # rather than flickering at Stop.
    ups_command = _command_for_scope("prompt-submit", scope)
    ups_groups, ups_existed = _strip_claude_tycho(_groups_of(hooks, "UserPromptSubmit", path))
    ups_groups.append({"hooks": [{"type": "command", "command": ups_command}]})
    hooks["UserPromptSubmit"] = ups_groups
    merged, statusline = _with_statusline(repo, {**data, "hooks": hooks}, path, scope)
    changed = _write(path, merged)
    if scope == REPO:
        state.write_install(repo, "claude", command)
    label = "claude" if scope == REPO else "claude (global)"
    hook_line = _status(label, "Stop hook", path, command, existed, changed)
    ss_line = _status(label, "SessionStart hook", path, ss_command, ss_existed, changed)
    ups_line = _status(label, "UserPromptSubmit hook", path, ups_command, ups_existed, changed)
    slash = _install_slash_commands(repo, scope)
    return "\n".join(filter(None, (hook_line, ss_line, ups_line, statusline, slash)))


# One flat file per subcommand, so each gets its own `/` autocomplete description.
_SLASH_SUBCOMMANDS = {
    "status": ("Is Tycho live here, and its last verdict", "statusline"),
    "doctor": ("Full diagnostics: is Tycho installed, current, and firing?", "doctor"),
    "verify": ("Verify the latest session and render a verdict", "verify $ARGUMENTS"),
    "help": ("What Tycho is, whether it's live here, and every command", "help"),
    "count": ("How many problems Tycho has caught here, and all-time", "count"),
    # `show` is the turn digest; the badge toggles are `badge-on`/`badge-off`, renamed in
    # 0.2.0 so `/tycho-show` doesn't shadow the release's most useful command.
    "show": ("The full receipt of a turn: what changed, what ran, what's unverified", "show $ARGUMENTS"),
    "log": ("What agents did in this repo, newest first", "log $ARGUMENTS"),
    "blame": ("Which turn touched this file, what it claimed, what backed it", "blame $ARGUMENTS"),
    "review": ("Which changes no test covered and no command exercised", "review $ARGUMENTS"),
    "attest": ("Print or check the Tycho-Attestation commit trailer", "attest $ARGUMENTS"),
    "badge-off": ("Hide the Tycho status indicator (the hook keeps verifying)", "statusline --off"),
    "badge-on": ("Show the Tycho status indicator again", "statusline --on"),
    "relay": ("Is the verdict relay on? (agent sees its verdict, works till VERIFIED)", "relay"),
    "relay-on": ("Turn ON the verdict relay — agent sees non-VERIFIED verdicts, works till VERIFIED (bounded)", "relay --on"),
    "relay-off": ("Turn OFF the verdict relay — verdicts stay human-only (the default)", "relay --off"),
    "override": ("Is the verdict override on? (agent may record per-check OVERRIDDEN, logged)", "override"),
    "override-on": ("Turn ON verdict override — agent may record a justified per-check OVERRIDDEN (logged)", "override --on"),
    "override-off": ("Turn OFF verdict override — the agent cannot override verdicts (the default)", "override --off"),
    "override-veto": ("Veto the agent's verdict override so the relay fires again (name a check, or bare for all)", "override --veto $ARGUMENTS"),
}


def _commands_dir(repo: Path, scope: str = REPO) -> Path:
    # `<repo>/.claude/commands`, not `state.root_for` — changing it would move every
    # already-installed command file.
    return (claude_dir(repo, GLOBAL) if scope == GLOBAL else repo / ".claude") / "commands"


def _q(s: str) -> str:
    """Quote a YAML frontmatter value. A bare colon-space in a description reads as a
    nested mapping and breaks Claude Code's parse, so always quote."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _slash_body(description: str, cli_args: str, argument_hint: str = "") -> str:
    """A prompt-style command file backed by the real CLI: relies only on the stable
    `.claude/commands/*.md` convention and `$ARGUMENTS`, not on `!`-exec / `allowed-tools`
    glob matching against a quoted interpreter path."""
    # Frontmatter must start at line 1 or Claude Code won't parse it, so the marker goes
    # in the body.
    hint = f"argument-hint: {_q(argument_hint)}\n" if argument_hint else ""
    return (
        "---\n"
        f"description: {_q(description)}\n{hint}"
        "---\n\n"
        f"{_SLASH_MARKER}\n\n"
        "Run this exact command with the Bash tool and show its output verbatim - "
        "nothing else, no commentary:\n\n"
        f"`{_command_for(cli_args)}`\n\n"
        "This is Tycho's own CLI (it also runs standalone in your terminal); it never edits code.\n"
    )


# (description, cli action, argument-hint). Globs must be single-quoted so the shell doesn't
# expand them before Tycho stores them — the body says so explicitly.
_SCOPE_SLASH = {
    "scope-list": ("List the files/dirs the agent may edit (the scope_drift allowlist)", "list", ""),
    "scope-set": ("Replace the scope_drift allowlist with these path globs", "set", "<glob>… e.g. 'src/**' 'tests/**'"),
    "scope-add": ("Add path globs to the scope_drift allowlist", "add", "<glob>… e.g. 'src/**' 'tests/**'"),
    "scope-remove": ("Remove path globs from the scope_drift allowlist", "remove", "<glob>… e.g. 'tests/**'"),
}


def _scope_slash_body(description: str, action: str, argument_hint: str) -> str:
    """A `/tycho-scope-*` command file. `list` reuses the generic body; set/add/remove tell
    the agent to single-quote each glob so the shell keeps it literal."""
    if action == "list":
        return _slash_body(description, "scope list")
    cmd = _command_for(f"scope {action}")
    return (
        "---\n"
        f"description: {_q(description)}\n"
        f"argument-hint: {_q(argument_hint)}\n"
        "---\n\n"
        f"{_SLASH_MARKER}\n\n"
        "Update this repo's Tycho edit-scope, then show the command's output verbatim. Run it with "
        "the Bash tool, passing **each glob as a separate single-quoted argument** so the shell keeps "
        "it literal (an unquoted `src/**` expands to files before Tycho stores it):\n\n"
        f"`{cmd} '<glob>' '<glob>' …`\n\n"
        "The globs to use: $ARGUMENTS\n\n"
        "This edits `.tycho.toml` only — it never touches your code.\n"
    )


def _slash_files(repo: Path, scope: str = REPO) -> dict[Path, str]:
    """Path → body for every `/tycho` command file we install (flat `tycho-<sub>.md`)."""
    d = _commands_dir(repo, scope)
    files = {d / "tycho.md": _slash_body(
        "Run Tycho - verify what the agent claimed", "$ARGUMENTS",
        argument_hint="<status|doctor|verify|scope|help>",
    )}
    for name, (desc, args) in _SLASH_SUBCOMMANDS.items():
        files[d / f"tycho-{name}.md"] = _slash_body(desc, args)
    for name, (desc, action, hint) in _SCOPE_SLASH.items():
        files[d / f"tycho-{name}.md"] = _scope_slash_body(desc, action, hint)
    return files


def _install_slash_commands(repo: Path, scope: str = REPO) -> str | None:
    """Write the `/tycho` command set. A command file without our marker is the user's and
    stays put."""
    target = _slash_files(repo, scope)
    d = _commands_dir(repo, scope)
    # Old `tycho/` namespace layout, plus `.bak` clutter — a command file is wholly ours.
    for path in [*_tycho_command_files(repo, scope), *d.glob("tycho*.tycho.bak")]:
        if path not in target and (path.suffix == ".bak" or _SLASH_MARKER in (_current_text(path) or "")):
            path.unlink()
    try:
        (d / "tycho").rmdir()  # tidy the old namespace dir if now empty
    except OSError:
        pass
    installed, skipped = [], []
    for path, body in target.items():
        existing = _current_text(path)
        if existing is not None and _SLASH_MARKER not in existing:
            skipped.append(path.name)
        elif _write_text(path, body, backup=False):
            installed.append(path)
    label = "claude" if scope == REPO else "claude (global)"
    lines = []
    if installed:
        lines.append(f"{label}: installed /tycho slash commands ({len(installed)}) → {d}")
    if skipped:
        lines.append(f"{label}: left your own command file(s) alone: {', '.join(sorted(set(skipped)))}")
    return "\n".join(lines) or None


def _user_statusline_command(repo: Path) -> str | None:
    """The command in the *user-level* Claude settings' statusLine, if any (read-only). The
    repo slot wins over the user-level one, so this tells us whether ours would shadow an
    existing badge. `$HOME` stays a signal, never a write target."""
    try:
        data = json.loads((harness_mod.home("claude") / "settings.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    sl = data.get("statusLine") if isinstance(data, dict) else None
    cmd = sl.get("command") if isinstance(sl, dict) else None
    return cmd if isinstance(cmd, str) and not _is_tycho_status(cmd) else None


_WRAPPED_STATUSLINE = "statusline-wrapped.json"


def _remember_statusline(repo: Path, statusline: dict | None) -> None:
    """Keep the whole statusLine object we displaced, so uninstall gives back `padding` and
    anything else the user set. `state`'s wrap record holds only the command, because that is
    all `tycho statusline` needs to run it. Best-effort: our own state dir, never a refusal."""
    path = state.dir_for(repo) / _WRAPPED_STATUSLINE
    try:
        if statusline is None:
            path.unlink(missing_ok=True)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(statusline, indent=2) + "\n", encoding="utf-8")
    except OSError:
        pass


def _recall_statusline(repo: Path) -> dict | None:
    try:
        data = json.loads((state.dir_for(repo) / _WRAPPED_STATUSLINE).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def _global_statusline(data: dict, path: Path) -> tuple[dict, str]:
    """The user-level status bar: take the slot only if it is empty. Repo scope can compose
    with a foreign line because it owns the write and uninstall puts the original back;
    machine-wide there is no such symmetry, so an occupied slot is left alone."""
    current = data.get("statusLine")
    if isinstance(current, dict) and not _is_tycho_status(current.get("command")):
        return data, ("claude (global): left your user-level statusLine alone — Tycho's badge "
                      "shows in repos where you run `tycho init`")
    base = current if isinstance(current, dict) else {}
    merged = {**base, "type": "command", "command": _command_for("statusline")}
    merged.setdefault("refreshInterval", _STATUS_REFRESH_MS)
    if merged == current:
        return data, ""
    return {**data, "statusLine": merged}, f"claude (global): installed statusLine → {path}"


def _with_statusline(repo: Path, data: dict, path: Path, scope: str = REPO) -> tuple[dict, str]:
    """Claim Claude Code's status bar, *composing* with any existing one.

    `statusLine` holds one command and a repo-level line wins over the user-level one, so
    rather than hide a third-party badge we take the slot and run the other command too. A
    foreign line in this repo's file is recorded (origin "repo") and restored on uninstall;
    a user-level one (origin "user") is left untouched and resurfaces once ours is gone.
    Shape verified against Claude Code 2.1.220: {"type": "command", "command": str}, plus
    optional padding/refreshInterval which are the user's to set — hence the merge.
    """
    if scope == GLOBAL:
        return _global_statusline(data, path)
    current = data.get("statusLine")
    command = status_command()
    ours = isinstance(current, dict) and _is_tycho_status(current.get("command"))
    foreign = current.get("command") if (isinstance(current, dict) and not ours) else None

    if isinstance(foreign, str):
        state.write_statusline_wrap(repo, foreign, origin="repo")
        _remember_statusline(repo, current)
    elif not (ours and (state.read_statusline_wrap(repo) or {}).get("origin") == "repo"):
        # A re-init sees its own line where the user's was, so re-deriving would clear the
        # only record of what the first init wrapped — and the `.bak` holds Tycho's line by
        # then. A "user" record re-derives freely; it's still in their own config.
        if (user_cmd := _user_statusline_command(repo)) is not None:
            state.write_statusline_wrap(repo, user_cmd, origin="user")
        else:
            state.clear_statusline_wrap(repo)
        _remember_statusline(repo, None)

    base = current if (ours and isinstance(current, dict)) else {}  # keep our own extra keys only
    merged = {**base, "type": "command", "command": command}
    # The badge renders at Stop, while our hook is still verifying — without polling it sits
    # on "pending" until the *next* prompt.
    merged.setdefault("refreshInterval", _STATUS_REFRESH_MS)
    if merged == current and state.read_statusline_wrap(repo) is None:
        return data, ""  # already ours, nothing to compose — the Stop-hook line speaks for it
    composing = " (composing with your existing status line)" if state.read_statusline_wrap(repo) else ""
    return {**data, "statusLine": merged}, f"claude: installed statusLine → {path}{composing}"


def _uninstall_claude(repo: Path, scope: str = REPO) -> str:
    """Take back our hooks and statusLine — only ours, in one write, or the backup churns
    (same reason install batches them). Scope-symmetric with `_install_claude`:
    `_is_tycho_owned` matches a guarded global command exactly as a bare repo-local one."""
    label = "claude" if scope == REPO else "claude (global)"
    path = settings_path(repo, scope)
    if not path.exists():
        return f"{label}: nothing to remove (no config)"
    data = _load(path)
    hooks = _hooks_of(data, path)
    groups, had_hook = _strip_claude_tycho(_groups_of(hooks, "Stop", path))
    ss_groups, had_ss = _strip_claude_tycho(_groups_of(hooks, "SessionStart", path))
    ups_groups, had_ups = _strip_claude_tycho(_groups_of(hooks, "UserPromptSubmit", path))
    current = data.get("statusLine")
    had_statusline = isinstance(current, dict) and _is_tycho_status(current.get("command"))
    slash = _uninstall_slash_commands(repo, scope)
    # A global install never wrote a compose record, and clearing the *repo's* would be wrong.
    wrap = state.read_statusline_wrap(repo) if scope == REPO else None
    wrapped = _recall_statusline(repo) if scope == REPO else None
    if scope == REPO:
        state.clear_statusline_wrap(repo)  # forget the compose target either way
        _remember_statusline(repo, None)
    if not had_hook and not had_ss and not had_ups and not had_statusline:
        return slash or f"{label}: nothing to remove"
    _prune(data, hooks, "Stop", groups)  # mutates `hooks` in place…
    _prune(data, hooks, "SessionStart", ss_groups)  # …then the second key…
    merged = _prune(data, hooks, "UserPromptSubmit", ups_groups)  # …then the third
    restored = False
    if had_statusline:
        merged = {k: v for k, v in merged.items() if k != "statusLine"}
        # A repo-level line we replaced is ours to put back; a user-level one resurfaces.
        if isinstance(wrap, dict) and wrap.get("origin") == "repo" and isinstance(wrap.get("command"), str):
            # Their whole object if we have it — `padding` was never ours to drop.
            merged = {**merged, "statusLine": wrapped or {"type": "command", "command": wrap["command"]}}
            restored = True
    _write(path, merged)
    _drop_backup(path)
    lines = []
    if had_hook:
        lines.append(f"{label}: removed Stop hook → {path}")
    if had_ss:
        lines.append(f"{label}: removed SessionStart hook → {path}")
    if had_ups:
        lines.append(f"{label}: removed UserPromptSubmit hook → {path}")
    if had_statusline:
        lines.append(f"{label}: restored your statusLine → {path}" if restored
                     else f"{label}: removed statusLine → {path}")
    if slash:
        lines.append(slash)
    return "\n".join(lines)


def _tycho_command_files(repo: Path, scope: str = REPO) -> list[Path]:
    """Every command file that could be ours — the flat `tycho.md`/`tycho-*.md` plus the old
    namespaced `tycho/*.md`, so uninstall cleans both layouts."""
    d = _commands_dir(repo, scope)
    return [*d.glob("tycho.md"), *d.glob("tycho-*.md"), *(d / "tycho").glob("*.md")]


def _uninstall_slash_commands(repo: Path, scope: str = REPO) -> str | None:
    """Remove every `/tycho` command we generated; leave hand-written files alone."""
    d = _commands_dir(repo, scope)
    removed = False
    for path in _tycho_command_files(repo, scope):
        text = _current_text(path)
        if text is not None and _SLASH_MARKER in text:
            path.unlink()
            removed = True
    for tidy in (d / "tycho", d):
        try:
            tidy.rmdir()  # only if now empty — never take a dir holding someone's file
        except OSError:
            pass
    label = "claude" if scope == REPO else "claude (global)"
    return f"{label}: removed /tycho slash commands → {d}" if removed else None
