"""Cursor, Codex and OpenCode. Two hook configs and one project plugin.

OpenCode has no Stop hook, so the plugin drives `tycho hook` off `session.idle`; that whole
file is ours, which is why it is the one thing uninstall deletes outright.
"""

from __future__ import annotations

import json
import shlex
from pathlib import Path

from . import spelling
from .. import state
from .configfile import (
    ConfigRefused,
    _current_text,
    _groups_of,
    _hooks_of,
    _load,
    _prune,
    _status,
    _strip_claude_tycho,
    _write,
    _write_text,
)
from .spelling import (
    _PLUGIN_MARKER,
    _command_for,
    _is_tycho_hook,
    config_path,
    hook_argv,
)



# HTML comment so it renders invisibly when previewed as Markdown.


def _install_cursor(repo: Path) -> str:
    # .cursor/hooks.json → hooks.stop is a flat list of {command, ...}; needs `version`.
    path = config_path(repo, "cursor")
    data = _load(path)
    hooks = _hooks_of(data, path)
    command = spelling.hook_command()
    stop = list(_groups_of(hooks, "stop", path))
    kept = [h for h in stop if not (isinstance(h, dict) and _is_tycho_hook(h.get("command")))]
    existed = len(kept) != len(stop)
    kept.append({"command": command})
    hooks["stop"] = kept
    changed = _write(path, {**data, "version": data.get("version", 1), "hooks": hooks})
    state.write_install(repo, "cursor", command)
    return _status("cursor", "stop hook", path, command, existed, changed)


def _install_codex(repo: Path) -> str:
    """Codex shares Claude's hooks shape: `hooks.<Event>` is a list of matcher-groups, and
    its output wire schema clones Claude's. One write, so the
    .bak doesn't churn — same reason `_install_claude` batches its keys.
    """
    path = config_path(repo, "codex")
    data = _load(path)
    hooks = _hooks_of(data, path)
    command = spelling.hook_command()
    groups, existed = _strip_claude_tycho(_groups_of(hooks, "Stop", path))
    groups.append({"hooks": [{"type": "command", "command": command}]})
    hooks["Stop"] = groups
    ss_command = _command_for("session-start")
    ss_groups, ss_existed = _strip_claude_tycho(_groups_of(hooks, "SessionStart", path))
    ss_groups.append({"hooks": [{"type": "command", "command": ss_command}]})
    hooks["SessionStart"] = ss_groups
    changed = _write(path, {**data, "hooks": hooks})
    state.write_install(repo, "codex", command)
    hook_line = _status("codex", "Stop hook", path, command, existed, changed)
    ss_line = _status("codex", "SessionStart hook", path, ss_command, ss_existed, changed)
    return "\n".join(filter(None, (hook_line, ss_line)))


def _install_opencode(repo: Path) -> str:
    # No Stop hook here: a project plugin drives `tycho hook` off `session.idle` and
    # `tycho session-start` off `session.created`, toasting via client.tui.showToast. The
    # transcript comes from opencode.db — `opencode export` truncates at 128 KB over a pipe.
    path = config_path(repo, "opencode")
    command = hook_argv(spelling.hook_command())
    notice = hook_argv(_command_for("session-start"))
    source = f'''{_PLUGIN_MARKER} OpenCode loads project plugins at startup.
const command = {json.dumps(command)}
const noticeCommand = {json.dumps(notice)}

export const TychoPlugin = async ({{ client, directory }}) => {{
  const run = async (argv, sessionID) => {{
    const proc = Bun.spawn([...argv], {{
      cwd: directory, stdin: "pipe", stdout: "pipe", stderr: "ignore",
    }})
    proc.stdin.write(JSON.stringify({{ harness: "opencode", sessionID, directory }}))
    proc.stdin.end()
    const text = (await new Response(proc.stdout).text()).trim()
    await proc.exited
    if (!text) return
    try {{
      const message = JSON.parse(text).message
      if (message) await client.tui.showToast({{
        body: {{ title: "Tycho", message, variant: "info" }},
      }})
    }} catch {{}}
  }}
  return {{
    event: async ({{ event }}) => {{
      if (event.type === "session.idle") {{
        const sessionID = event.properties?.sessionID
        if (sessionID) await run(command, sessionID)
      }} else if (event.type === "session.created") {{
        await run(noticeCommand, event.properties?.sessionID)
      }}
    }},
  }}
}}
'''
    # A hand-written tycho.js is not ours — refuse rather than overwrite it.
    existed = path.exists()
    if existed and _PLUGIN_MARKER not in (_current_text(path) or ""):
        raise ConfigRefused(f"{path} wasn't generated by tycho init — move it aside, then re-run")
    changed = _write_text(path, source)
    state.write_install(repo, "opencode", shlex.join(command))
    return _status("opencode", "session.idle + session.created plugin", path, shlex.join(command), existed, changed)


def _uninstall_codex(repo: Path) -> str:
    """Remove the Stop and SessionStart hooks — only ours, in one write."""
    path = repo / ".codex" / "hooks.json"
    if not path.exists():
        return "codex: nothing to remove (no config)"
    data = _load(path)
    hooks = _hooks_of(data, path)
    groups, had_hook = _strip_claude_tycho(_groups_of(hooks, "Stop", path))
    ss_groups, had_ss = _strip_claude_tycho(_groups_of(hooks, "SessionStart", path))
    if not had_hook and not had_ss:
        return "codex: nothing to remove"
    _prune(data, hooks, "Stop", groups)  # mutates `hooks` in place…
    merged = _prune(data, hooks, "SessionStart", ss_groups)  # …then the second key
    _write(path, merged)
    lines = []
    if had_hook:
        lines.append(f"codex: removed Stop hook → {path}")
    if had_ss:
        lines.append(f"codex: removed SessionStart hook → {path}")
    return "\n".join(lines)


def _uninstall_cursor(repo: Path) -> str:
    # .cursor/hooks.json → hooks.stop is a flat list of {command, ...}.
    path = repo / ".cursor" / "hooks.json"
    if not path.exists():
        return "cursor: nothing to remove (no config)"
    data = _load(path)
    hooks = _hooks_of(data, path)
    stop = list(_groups_of(hooks, "stop", path))
    kept = [h for h in stop if not (isinstance(h, dict) and _is_tycho_hook(h.get("command")))]
    if len(kept) == len(stop):
        return "cursor: nothing to remove"
    _write(path, _prune(data, hooks, "stop", kept))
    return f"cursor: removed stop hook → {path}"


def _uninstall_opencode(repo: Path) -> str:
    # The whole plugin file is ours — but only if we generated it.
    path = repo / ".opencode" / "plugins" / "tycho.js"
    if not path.exists():
        return "opencode: nothing to remove"
    try:
        generated = _PLUGIN_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        generated = False
    if not generated:
        return f"opencode: left {path} alone (not generated by tycho init)"
    path.unlink()
    try:
        path.parent.rmdir()  # tidy the plugins/ dir we made — only if now empty
    except OSError:
        pass  # user has other plugins, or the dir predates us: leave it
    return f"opencode: removed plugin → {path}"
