"""How a Tycho command is spelled, and how we recognize one we wrote.

Install and uninstall both route through `_is_tycho_owned`, so "which entry is ours" can
never drift between them.
"""

from __future__ import annotations

import re
import shlex
import shutil
import sys
from pathlib import Path

from ...read import harness as harness_mod
from ...store import state


# Proof a generated file is ours; uninstall deletes only files carrying the marker.
_PLUGIN_MARKER = "// Generated by tycho init."

HARNESSES = ("claude", "cursor", "codex", "opencode")

# Install scopes: "repo" (default) or the user-level harness config (strategy §6.7).


# Install scopes: "repo" (default) or the user-level harness config (strategy §6.7).
REPO = "repo"


GLOBAL = "global"

# The git hook that stamps the `Tycho-Attestation:` trailer (strategy §6.6). Fenced by


# Per-repo config dir; created by the harness on first use, so its presence is a signal.
_LOCAL_DIR = {"claude": ".claude", "cursor": ".cursor", "codex": ".codex", "opencode": ".opencode"}

# Milliseconds. A user who sets their own value keeps it.


def _quote_program(path: str) -> str:
    """Double-quote a program path containing a space — unquoted, a Windows path splits
    into two argv tokens under both cmd and /bin/sh."""
    return f'"{path}"' if " " in path and not path.startswith('"') else path


def hook_command() -> str:
    """A command the harness's plain `/bin/sh` can run. The Stop hook fires without an
    activated venv, so a bare ``tycho`` only works from a global/pipx install; otherwise
    resolve an absolute path, which runs regardless of PATH."""
    return _command_for("hook")


def status_command() -> str:
    """Same resolution as `hook_command`, for the status bar."""
    return _command_for("statusline")


def _command_for(subcommand: str) -> str:
    # Claude Code runs hook commands through Git Bash, which eats unquoted backslashes, so a
    # native Windows path never fires. A blunt swap, not Path.as_posix (host-flavored).
    found = shutil.which("tycho")
    program = _quote_program((found or sys.executable).replace("\\", "/"))
    return f"{program} {subcommand}" if found else f"{program} -m tycho.cli {subcommand}"


def attest_command() -> str:
    """The command the git `prepare-commit-msg` hook runs to stamp the trailer. Module form
    because `attest.py` owns that entrypoint outright; absolute interpreter and forward
    slashes as in `hook_command` (git uses Git Bash on Windows too). A frozen build has no
    importable interpreter, so it uses the console-script form.

    The module path is baked into an installed hook, so moving `attest.py` means an existing
    hook points at a module that no longer imports. It fails open — no trailer, never a
    broken commit — and the `state.SCHEMA` bump is what routes the upgrader to `tycho init`.
    """
    program = _quote_program(sys.executable.replace("\\", "/"))
    if getattr(sys, "frozen", False):
        return f"{program} attest --write"
    return f"{program} -m tycho.wire.attest"


def hook_argv(command: str) -> list[str]:
    """Split a hook command into argv. ``posix=False`` so a ``C:\\...`` path keeps its
    backslashes (POSIX mode treats ``\\`` as an escape), then strip the quotes it leaves.
    An unbalanced quote yields ``[]``."""
    try:
        argv = shlex.split(command, posix=False)
    except ValueError:
        return []
    return [a.strip('"') for a in argv]


def _is_ours(command: object, subcommand: str) -> bool:
    """True if an existing entry is one of ours (any resolved form) — install and uninstall
    both route through this. Tolerant of the Windows ``tycho.exe`` suffix, surrounding
    quotes, and both path separators. Pure matching; no filesystem access."""
    if not isinstance(command, str) or not command.endswith(f" {subcommand}"):
        return False
    program = command[: -len(f" {subcommand}")].rstrip()
    if program.endswith("tycho.cli"):  # `<python> -m tycho.cli <subcommand>`
        return True
    base = re.split(r"[\\/]", program.strip('"'))[-1]  # basename, either separator
    return base.lower() in ("tycho", "tycho.exe")


def _is_tycho_hook(command: object) -> bool:
    return _is_ours(command, "hook")


def _is_tycho_status(command: object) -> bool:
    # `statusline` is canonical, `status` the old name: match both so init self-heals an
    # old statusLine and uninstall removes it either way.
    return _is_ours(command, "statusline") or _is_ours(command, "status")


def _is_tycho_session_start(command: object) -> bool:
    return _is_ours(command, "session-start")


def _is_tycho_prompt_submit(command: object) -> bool:
    return _is_ours(command, "prompt-submit")


def _is_tycho_owned(command: object) -> bool:
    """Any hook command Tycho installs into a matcher-group: Stop, SessionStart or
    UserPromptSubmit."""
    return (
        _is_tycho_hook(command)
        or _is_tycho_session_start(command)
        or _is_tycho_prompt_submit(command)
    )


def config_path(repo: Path, name: str) -> Path:
    """Where `name`'s repo-local config lives. Resolved from the same root as `.tycho/`, or
    `doctor` run from a subdirectory would find the root's install record but look for the
    harness config beside itself."""
    return state.root_for(repo) / {
        "claude": ".claude/settings.json",
        "cursor": ".cursor/hooks.json",
        "codex": ".codex/hooks.json",
        "opencode": ".opencode/plugins/tycho.js",
    }[name]


# Two `exit 0`s: outside a git repo we do nothing (else a user-level hook sprinkles `.tycho/`
# across the filesystem), and in a repo with its own Tycho hook we defer to it — checked at
# run time, so it holds for repos wired before `--global` existed. Plain `/bin/sh`, no
# bashisms: that's what Claude Code runs hook commands with.
# ponytail: grepping for our own hook spelling is a cheap proxy for "repo-local owns this";
# a false match only makes global stay quiet where repo-local is already wired.
_GLOBAL_GUARD = (
    'git rev-parse --show-toplevel >/dev/null 2>&1 || exit 0; '
    'grep -qsE "tycho(\\.exe)? hook|tycho\\.cli hook" '
    '"$(git rev-parse --show-toplevel)/.claude/settings.json" && exit 0; '
)


def _command_for_scope(subcommand: str, scope: str) -> str:
    """The hook command for `subcommand`, guarded when going into the user-level config.
    Must still end in `" <subcommand>"` so `_is_ours` recognizes a guarded entry like a bare
    one. Routes Stop through `hook_command()`: that is the seam doctor's tests substitute,
    so it must stay the one source of the Stop command."""
    command = hook_command() if subcommand == "hook" else _command_for(subcommand)
    return _GLOBAL_GUARD + command if scope == GLOBAL else command


def claude_dir(repo: Path, scope: str = REPO) -> Path:
    """The `.claude` tree this scope writes into. Via `harness_mod.home`, the same function
    detection reads, so `CLAUDE_CONFIG_DIR` (or a test override) redirects both at once and
    the suite never touches a real `~/.claude`."""
    return harness_mod.home("claude") if scope == GLOBAL else state.root_for(repo) / ".claude"


def settings_path(repo: Path, scope: str = REPO) -> Path:
    return claude_dir(repo, scope) / "settings.json"
