"""`tycho init` / `tycho uninstall` — manage the completion hook in each harness's config.

By default everything written here is **repo-local**: only `<repo>/.claude`, `.cursor`,
`.codex`, `.opencode` and `<repo>/.git/hooks` are ever touched. A harness's home directory
under `$HOME` is *read* (never written) as a detection signal — it tells us the harness
exists on this machine and is therefore worth hooking up in this repo.

Two things break that repo-local default, both deliberately and both opt-in:

- **The git `prepare-commit-msg` hook** (`_install_git_hook`), which stamps the
  `Tycho-Attestation:` trailer. Still repo-local — it lives in this repo's hooks dir — but
  it is the one thing here that runs inside someone's `git commit`, so it is written to
  never block: our block can't exit, can't fail, and is skipped whole if we can't parse the
  hook we'd be extending.
- **`--global`** (`init_global`), which writes the *user-level* Claude Code config so Tycho
  is live in every repo on the machine (strategy §6.7). Never implied, never a silent
  upgrade from a per-repo install: it asks, loudly, and prints how to undo it. The command
  it installs carries a shell guard that fires only inside a git repo and defers to any
  per-repo install, so the blast radius stays "repos you actually work in" and the two
  installs can't double-fire.

Idempotent both ways: re-running init never duplicates the entry and never clobbers
hooks the user already configured; uninstall removes only Tycho-owned entries and is
a no-op once they're gone. The config shapes differ per harness, so each gets its own
installer/uninstaller; the load/merge/write skeleton is shared.

Install and uninstall share `_is_tycho_hook` + `_strip_claude_tycho` on purpose — the
rule for "which entry is ours" must never drift between the two, or uninstall would
orphan exactly the entries install replaces.

This runs against a real developer's real settings, so every mutation is defensive:
refuse what we can't parse instead of "recovering" it to `{}` and writing that back,
back up before touching, write atomically so an interrupted run can't truncate the
original, and skip the write entirely when the file is already correct.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import shlex
from pathlib import Path

from . import config as config_mod
from . import gitstate
from . import harness as harness_mod
from . import opencode as opencode_mod
from . import state


# The header install stamps into the OpenCode plugin, and the proof uninstall looks
# for before deleting it. One constant so the two can't drift apart.
_PLUGIN_MARKER = "// Generated by tycho init."

# Stamped into the `/tycho` slash-command file; the proof uninstall looks for before
# deleting it, so a hand-written tycho.md is never removed. Kept as an HTML comment so it
# renders invisibly if the file is ever previewed as Markdown.
_SLASH_MARKER = "<!-- Generated by tycho init. -->"

# Marker for "we declined to touch this file". Built into the status line from the same
# constant the CLI matches on, so the exit code can't drift from the message.
REFUSED = ": refused — "

_BACKUP_SUFFIX = ".tycho.bak"
_TMP_SUFFIX = ".tycho-tmp"

HARNESSES = ("claude", "cursor", "codex", "opencode")

# Install scopes. "repo" is everything that existed before this and is still the default;
# "global" writes the user-level harness config instead (strategy §6.7). One vocabulary so
# the path helpers, the installers and the uninstallers can't disagree about which tree
# they're in.
REPO = "repo"
GLOBAL = "global"

# The git hook that stamps the `Tycho-Attestation:` trailer (strategy §6.6). Fenced by
# markers rather than owning the whole file, because a repo may already have a
# prepare-commit-msg hook and ours has no business replacing it.
_GIT_HOOK = "prepare-commit-msg"
_GIT_BEGIN = "# >>> tycho"
_GIT_END = "# <<< tycho"
_GIT_BLOCK_RE = re.compile(rf"[ \t]*{re.escape(_GIT_BEGIN)}\b.*?{re.escape(_GIT_END)}[ \t]*\n?",
                           re.DOTALL)
# Interpreters whose scripts we're willing to append a `/bin/sh` block to. Anything else
# (a python hook, a compiled binary, no shebang at all) is refused, not rewritten — same
# rule as a config we can't parse.
_SH_SHEBANG = re.compile(r"^#!.*\b(sh|bash|dash|ash|zsh|ksh)\b")

# Where each harness keeps its per-repo config. A harness creates this on first use in
# a repo, which makes its presence a detection signal in its own right.
_LOCAL_DIR = {"claude": ".claude", "cursor": ".cursor", "codex": ".codex", "opencode": ".opencode"}

# statusLine poll cadence, so the badge settles on the verdict shortly after a turn rather
# than lagging to the next prompt. Claude Code's `refreshInterval` is milliseconds
# (contract in docs/harness-support.md); 1s is responsive and the read it triggers is cheap
# (one small JSON file, no engine). A user who sets their own value keeps it.
_STATUS_REFRESH_MS = 1000


class ConfigRefused(Exception):
    """This file must not be written — malformed, unreadable, or read-only.

    The message always carries the fix, not just the complaint: whoever sees it is
    mid-install and needs to know what to do about it.
    """


def _quote_program(path: str) -> str:
    """Wrap a program path in double quotes if it contains a space.

    Absolute paths on Windows routinely hold spaces (``C:\\Users\\...\\Swail Labs\\``);
    an unquoted one splits into two argv tokens under both cmd and /bin/sh, so the
    harness runs ``...\\Swail`` and fails. Double quotes work in both shells.
    """
    return f'"{path}"' if " " in path and not path.startswith('"') else path


def hook_command() -> str:
    """A command the harness's plain `/bin/sh` can actually run.

    The Stop hook fires without an activated venv, so a bare ``tycho`` only works
    when it's on the global PATH (a pipx/global install). Otherwise resolve an
    absolute path: the installed console script if we can find one, else the
    current interpreter with ``-m``. Absolute paths run regardless of PATH.
    """
    return _command_for("hook")


def status_command() -> str:
    """Same resolution as `hook_command`, for the status bar."""
    return _command_for("statusline")


def _command_for(subcommand: str) -> str:
    # Claude Code runs hook/statusLine commands through Git Bash, which consumes unquoted
    # backslashes as escapes — so a native Windows path silently fails to resolve and the
    # hook/status just never fires. Emit forward slashes, per Claude Code's own shipped
    # guidance. A blunt separator swap (not Path.as_posix, which is host-flavored) so it's
    # correct for a Windows path on any host — sys.executable / the console script never
    # carry a literal backslash on POSIX.
    found = shutil.which("tycho")
    program = _quote_program((found or sys.executable).replace("\\", "/"))
    return f"{program} {subcommand}" if found else f"{program} -m tycho.cli {subcommand}"


def attest_command() -> str:
    """The command the git `prepare-commit-msg` hook runs to stamp the trailer.

    Module form (`<python> -m tycho.attest`) rather than `tycho attest`, because
    `attest.py` owns that entrypoint outright — the hook therefore works the moment it is
    installed, with no CLI surface to keep in sync. The interpreter is the absolute one that
    ran `tycho init`, so the hook resolves without a PATH and without an activated venv,
    exactly like `hook_command`. Forward slashes for the same Git Bash reason —
    git runs hooks through its bundled shell on Windows too.

    A frozen/standalone build has no importable interpreter (`sys.executable` *is* the tycho
    binary), so it falls back to the `tycho attest --write` console-script form.
    """
    program = _quote_program(sys.executable.replace("\\", "/"))
    if getattr(sys, "frozen", False):
        return f"{program} attest --write"
    return f"{program} -m tycho.attest"


def hook_argv(command: str) -> list[str]:
    """Split a hook command into argv, keeping Windows paths intact.

    ``posix=False`` so a ``C:\\...`` path keeps its backslashes (POSIX mode treats ``\\``
    as an escape and mangles it), then strip the quotes it leaves on a token. An
    unbalanced quote yields ``[]`` ("nothing runnable"). Behaves like the old POSIX split
    on the quote- and backslash-free commands *nix produces.
    """
    try:
        argv = shlex.split(command, posix=False)
    except ValueError:
        return []
    return [a.strip('"') for a in argv]


def _is_ours(command: object, subcommand: str) -> bool:
    """True if an existing entry is one of ours (any resolved form).

    Install and uninstall both route through this, so "which entry is ours" can't drift
    between them — uninstall must remove exactly what install would replace. Tolerant of
    the platform executable suffix (on Windows the console script is ``tycho.exe``, so the
    command ends ``tycho.EXE hook`` not ``tycho hook``), surrounding quotes, and both path
    separators, so the answer is identical on every OS (matching, not resolution: no
    filesystem access).
    """
    if not isinstance(command, str) or not command.endswith(f" {subcommand}"):
        return False
    program = command[: -len(f" {subcommand}")].rstrip()
    if program.endswith("tycho.cli"):  # `<python> -m tycho.cli <subcommand>`
        return True
    base = re.split(r"[\\/]", program.strip('"'))[-1]  # basename, either separator
    return base.lower() in ("tycho", "tycho.exe")


def _is_tycho_hook(command: object) -> bool:
    return _is_ours(command, "hook")


def _is_tycho_status(command: object) -> bool:
    # `statusline` is canonical; `status` is the pre-name. Match both so init
    # self-heals an old `tycho status` statusLine into `tycho statusline`, and uninstall
    # removes it either way.
    return _is_ours(command, "statusline") or _is_ours(command, "status")


def _is_tycho_session_start(command: object) -> bool:
    return _is_ours(command, "session-start")


def _is_tycho_prompt_submit(command: object) -> bool:
    return _is_ours(command, "prompt-submit")


def _is_tycho_owned(command: object) -> bool:
    """Any hook command Tycho installs into a matcher-group — Stop (`hook`), bootup
    (`session-start`), or run-start (`prompt-submit`). All live in `hooks.*` groups, so one
    predicate strips any of them."""
    return (
        _is_tycho_hook(command)
        or _is_tycho_session_start(command)
        or _is_tycho_prompt_submit(command)
    )


def config_path(repo: Path, name: str) -> Path:
    """Where `name`'s repo-local config lives. One map, so init and doctor can't disagree.

    Resolved from the same root as `.tycho/`: a harness config is repo-local in
    exactly the way our state is, and if the two disagree, `doctor` run from a subdirectory
    finds the root's install record, looks for the harness config beside *itself*, and cries
    HOOK BROKEN over a hook that is wired fine.
    """
    return state.root_for(repo) / {
        "claude": ".claude/settings.json",
        "cursor": ".cursor/hooks.json",
        "codex": ".codex/hooks.json",
        "opencode": ".opencode/plugins/tycho.js",
    }[name]


# The guard every *global* hook command carries. Two `exit 0`s, in this order:
#
#   1. not inside a git repo  → do nothing. A user-level hook fires in every directory the
#      agent is ever launched from, including scratch dirs and other people's trees; without
#      this, Tycho would sprinkle `.tycho/` state across the whole filesystem. A repo is the
#      only place our state has a meaning, so it is the only place we run.
#   2. this repo has its own Tycho hook → do nothing, and let the repo-local install own it.
#      That is the anti-double-fire rule, enforced at *run* time rather than install time,
#      so it holds for repos that were wired long before `--global` was ever run.
#
# Written for `/bin/sh` because that is what Claude Code runs a hook command with (Git Bash
# on Windows — hence no `[[`, no arrays, no bashisms). Failing open is the whole design:
# every branch of this leaves the exit status at 0. ponytail: a `grep` for our own hook
# spelling is a cheap proxy for "the repo-local install owns this"; a false match only ever
# means global stays quiet somewhere a repo-local install was already configured.
_GLOBAL_GUARD = (
    'git rev-parse --show-toplevel >/dev/null 2>&1 || exit 0; '
    'grep -qsE "tycho(\\.exe)? hook|tycho\\.cli hook" '
    '"$(git rev-parse --show-toplevel)/.claude/settings.json" && exit 0; '
)


def _command_for_scope(subcommand: str, scope: str) -> str:
    """The hook command for `subcommand`, guarded when it's going into the user-level config.

    Deliberately still ends in `" <subcommand>"`, so `_is_ours` recognizes a guarded entry
    exactly as it recognizes a bare one — uninstall must be able to remove what install
    wrote, whichever scope wrote it.

    Routes the Stop hook through `hook_command()` rather than `_command_for` directly:
    that is the named seam `doctor`'s tests substitute to simulate a hook that resolves to
    nothing, and it must stay the one place the Stop command comes from.
    """
    command = hook_command() if subcommand == "hook" else _command_for(subcommand)
    return _GLOBAL_GUARD + command if scope == GLOBAL else command


def claude_dir(repo: Path, scope: str = REPO) -> Path:
    """The `.claude` tree this scope writes into: the repo's, or the user's `~/.claude`.

    `harness_mod.home` is the same function detection reads, so a test (or a user with
    `CLAUDE_CONFIG_DIR` set) redirects both with one override and the suite never touches a
    real `~/.claude`.
    """
    return harness_mod.home("claude") if scope == GLOBAL else state.root_for(repo) / ".claude"


def settings_path(repo: Path, scope: str = REPO) -> Path:
    return claude_dir(repo, scope) / "settings.json"


def global_installed() -> bool:
    """Is Tycho wired into the *user-level* Claude config right now?

    The config is the truth, not a marker file we wrote (same rule as `installed_command`):
    a user who hand-removes the entry has uninstalled, and Tycho must agree. Never raises —
    a user-level config we can't parse reads as "not installed", because we would refuse to
    write it anyway.
    """
    try:
        data = _load(settings_path(Path.cwd(), GLOBAL))
    except ConfigRefused:
        return False
    hooks = data.get("hooks") if isinstance(data.get("hooks"), dict) else {}
    return any(
        isinstance(entry, dict) and _is_tycho_owned(entry.get("command"))
        for group in (hooks.get("Stop") or [])
        if isinstance(group, dict)
        for entry in (group.get("hooks") or [])
    )


def installed_command(repo: Path, name: str) -> str | None:
    """The tycho hook command `name` would actually run, read back from its own config.

    The config is the truth — not what we *meant* to install. `doctor` diagnoses what the
    harness will really execute, which is the only thing that decides whether Tycho fires.
    Raises ConfigRefused if the config can't be read (same rule as everywhere else).
    """
    path = config_path(repo, name)
    if name == "opencode":
        text = _current_text(path)
        if text is None or _PLUGIN_MARKER not in text:
            return None
        # The plugin holds its argv as a JSON array: `const command = ["...", "hook"]`.
        match = re.search(r"^const command = (\[.*\])$", text, re.MULTILINE)
        if not match:
            return None
        try:
            return shlex.join(json.loads(match.group(1)))
        except (json.JSONDecodeError, TypeError):
            return None
    data = _load(path)
    hooks = data.get("hooks") if isinstance(data.get("hooks"), dict) else {}
    if name == "cursor":
        entries = hooks.get("stop") or []
    else:
        entries = [h for g in (hooks.get("Stop") or []) if isinstance(g, dict) for h in (g.get("hooks") or [])]
    for entry in entries:
        if isinstance(entry, dict) and _is_tycho_hook(entry.get("command")):
            return entry["command"]
    return None


# --- detection ---------------------------------------------------------------
#
# "Is this harness worth hooking up here?" Two cheap directory probes, either sufficient:
# the harness has run in this repo (dotdir exists) or is installed for the user (home
# exists) — never executed. A false negative just means the user passes `--harness`.


def detect(repo: Path) -> list[str]:
    """Enabled harnesses that appear to be present, in stable order.

    Detection is gated to `harness_mod.ENABLED_NAMES` (Claude only for now): the other
    installers still exist and are tested, but init must not prompt to wire them up.
    """
    return [name for name in HARNESSES if name in harness_mod.ENABLED_NAMES and _is_present(name, repo)]


def _is_present(name: str, repo: Path) -> bool:
    if (repo / _LOCAL_DIR[name]).is_dir():
        return True
    if name == "opencode":
        # OpenCode's data lives in an XDG data dir, not a ~/.<name> dotdir.
        return opencode_mod.db_path().parent.is_dir()
    return harness_mod.home(name).is_dir()


def _ask(name: str) -> bool:
    """Prompt before touching one harness. Default yes; anything but n/no is yes."""
    try:
        reply = input(f"tycho: install the {name} completion hook in this repo? [Y/n] ")
    except EOFError:
        return False
    return reply.strip().lower() not in ("n", "no")


def init(
    repo: Path,
    only: str | None = None,
    assume_yes: bool = False,
    confirm=None,
    relay_confirm=None,
) -> list[str]:
    """Install the repo-local Stop hook per harness; return status lines.

    Touches only harnesses that are actually present, and asks before each one. With
    ``only`` set (a harness name), install just that harness and skip detection — the
    user named it, so its absence is not our call to second-guess. ``assume_yes`` skips
    the prompts for scripted/CI installs; ``confirm`` overrides the prompt (tests).
    """
    installers = {
        "claude": _install_claude,
        "cursor": _install_cursor,
        "codex": _install_codex,
        "opencode": _install_opencode,
    }
    if only:
        names = [only]
    else:
        # A machine-wide install already covers the harness here, and installing again would
        # give this repo two Stop hooks firing on every turn. Wire the one thing global
        # can't (the commit trailer lives in *this* repo's .git/hooks) and say so. Explicit
        # `--harness` still installs — the user named it, which is not ours to second-guess.
        if global_installed():
            return [
                "tycho: a global install is active — the Claude Code hooks already cover this "
                f"repo ({settings_path(repo, GLOBAL)}).",
                *_git_lines(repo),
                "  Per-repo anyway: `tycho init --harness claude` (global then defers to it).",
                "  Remove the global install: `tycho uninstall --global`.",
            ]
        names = detect(repo)
        if not names:
            return ["no supported harness detected here — pass --harness <name> to install anyway"]
    ask = confirm or _ask
    if not assume_yes and confirm is None and not sys.stdin.isatty():
        # Nobody's there to answer, and installing unasked is exactly what this ticket
        # exists to stop. Say how to proceed rather than silently doing nothing.
        return [f"tycho init needs a terminal to confirm ({', '.join(names)}) — pass --yes to install non-interactively"]

    lines = []
    installed = []
    for name in names:
        if not assume_yes and not ask(name):
            lines.append(f"{name}: skipped")
            continue
        try:
            lines.append(installers[name](repo))
            installed.append(name)
        except ConfigRefused as exc:
            lines.append(f"{name}{REFUSED}{exc}")
    installed_any = bool(installed)
    # Did the user bring their own .tycho.toml? Capture it *before* `ensure` creates one, so the
    # relay setup below can tell "user already configured this" from "we just seeded it".
    config_existed = config_mod.path(repo).is_file()
    # Seed a .tycho.toml so scope is discoverable and editable — but only once a
    # harness actually got wired: no install (declined/refused) means don't leave config
    # behind. Harness-agnostic, empty (behaviour unchanged until a glob is added), never
    # clobbers an existing one. Appended last so a harness line stays lines[0].
    if installed_any and config_mod.ensure(repo):
        lines.append(
            f"created {config_mod.CONFIG_NAME} — no scope set yet, so nothing changes until you "
            f"run `tycho scope add '<glob>'`"
        )
    # The commit trailer (strategy §6.6). Gated on a harness actually being wired, same rule
    # as the config seed: no install means leave the user's repo alone, including their hooks.
    if installed_any:
        lines += _git_lines(repo)
    lines += _offer_relay(
        repo, any(name in installed for name in ("claude", "codex")),
        assume_yes, config_existed, relay_confirm,
    )
    return lines


def _git_lines(repo: Path) -> list[str]:
    """Everything `init` does to git itself: the commit-trailer hook, and ignoring `.tycho/`.

    Wrapped rather than inlined because both `init` paths need it and neither may raise:
    a repo whose `prepare-commit-msg` we won't touch is a *reported* outcome, never an
    exception that aborts the rest of an install that otherwise succeeded. The two are
    independent — a refused hook must not cost you the gitignore entry, or the reverse.
    """
    lines = []
    for step in (_install_git_hook, _install_gitignore):
        try:
            lines.append(step(repo))
        except ConfigRefused as exc:
            lines.append(f"git{REFUSED}{exc}")
    return [line for line in lines if line]


def _ask_relay() -> bool:
    """Prompt (default NO) to enable the verdict relay — it feeds Tycho's verdict into the
    agent and spends extra tokens, so it must be *explicitly* opted into. Only
    'y'/'yes' enables; a bare Enter or EOF leaves it off."""
    try:
        reply = input(
            "tycho: let the agent see its own verdict and keep working until VERIFIED? This feeds "
            "Tycho's verdict back into the agent (extra tokens; the loop is bounded). [y/N] "
        )
    except EOFError:
        return False
    return reply.strip().lower() in ("y", "yes")


def _offer_relay(
    repo: Path, relay_harness_installed: bool, assume_yes: bool,
    config_existed: bool, relay_confirm=None,
) -> list[str]:
    """Set up the verdict relay at install time (/114, Claude and Codex). If the user already
    had a `.tycho.toml`, *respect* its relay choice and just say how to change it; otherwise ask
    (default NO) and write the initial state. A scripted install (`--yes`, no TTY) never enables
    it silently. ``relay_confirm`` overrides the prompt for tests. Returns status lines to print."""
    if not relay_harness_installed:
        return []
    if config_existed:
        # The user brought their own config — don't re-ask or override it. Point at how to change.
        state_txt = "ON" if state.relay_enabled(repo) else "OFF"
        return [
            f"tycho: verdict relay is {state_txt} (from your {config_mod.CONFIG_NAME}). Change it "
            f"with `tycho relay --on|--off`."
        ]
    interactive = relay_confirm is not None or (not assume_yes and sys.stdin.isatty())
    if not interactive:
        return []  # scripted / no TTY: leave the default (off), already written by config.ensure
    if (relay_confirm or _ask_relay)():
        state.set_relay_enabled(repo, True)
        return [
            f"tycho: verdict relay ON — the agent will see a non-VERIFIED verdict and keep working "
            f"until VERIFIED, up to {state.relay_max()} automatic re-checks per turn (extra tokens). "
            f"Turn it off with `tycho relay --off` or /tycho-relay-off."
        ]
    return [
        "tycho: verdict relay OFF (the default) — turn it on with `tycho relay --on` "
        "to have the agent work until VERIFIED."
    ]


def _wired_here(repo: Path, name: str) -> bool:
    """Does `name`'s config already carry our hook? A config we can't read counts as wired —
    we don't offer to overwrite something we can't inspect."""
    try:
        return installed_command(repo, name) is not None
    except ConfigRefused:
        return True


def _ask_setup(harnesses: list[str]) -> bool:
    reply = input(f"Set up Tycho in this repo ({', '.join(harnesses)})? [Y/n] ").strip().lower()
    return reply in ("", "y", "yes")


def offer_first_run(repo: Path, confirm=None) -> list[str]:
    """First-run nudge: a supported agent is here but Tycho isn't wired.

    Offer to set it up — interactively when there's a terminal (`Set up Tycho here? [Y/n]` →
    runs init), or by printing the one-liner when there isn't. Fires **once per repo** (a
    declined offer is never re-nagged) and **never writes config without consent**:
    the "already offered" marker lives outside the repo, and a decline touches nothing.
    Returns status lines for the caller to print; `[]` when there's nothing to offer.
    """
    if state.already_offered(repo):
        return []
    detected = detect(repo)
    if not detected or state.read_install(repo) or any(_wired_here(repo, n) for n in detected):
        return []  # nothing here, or already set up
    state.mark_offered(repo)  # offered — regardless of the answer, don't ask again
    ask = confirm or _ask_setup
    interactive = confirm is not None or sys.stdin.isatty()  # a real TTY, or a test's confirm
    if interactive and ask(detected):
        return ["Tycho: setting up here…", *init(repo, only=None, assume_yes=True)]
    return [
        f"Tycho isn't set up in this repo yet — a supported agent ({', '.join(detected)}) is here.",
        "  Run `tycho init` to wire it up (offered once; it won't ask again).",
    ]


# --- zero setup: the machine-wide install (strategy §6.7) --------------------
#
# "`git init`-grade — one global command, every repo forever, harness auto-detected, no
# `.tycho.toml` required." All four hold here: `tycho init --global` writes the user-level
# Claude Code config once, `detect` still decides whether the harness is even present, and
# nothing below writes a `.tycho.toml` — zero-config stays zero-config (`scope_drift`
# returns UNSUPPORTED with no config, and must keep doing so).
#
# The thing a global install buys in reach it pays for in blast radius, so the safety design
# is the feature, not the paperwork around it:
#
#   - **Opt-in and loud.** Never implied by `tycho init`, never a silent upgrade of a
#     per-repo install. `_ask_global` prints every path it will touch and defaults to NO.
#   - **Guarded at run time**, not just at install time — see `_GLOBAL_GUARD`. Outside a git
#     repo we do nothing at all; inside a repo with its own install we defer to it.
#   - **Additive only.** Same merge/backup/refuse machinery as the repo-local installer, so
#     a user-level config we can't parse is left alone, and an existing user-level statusLine
#     is not composed with — it's simply not touched (`_global_statusline`).
#   - **No global git config.** Deliberately no `core.hooksPath`: setting it machine-wide
#     silently disables *every* repo's own `.git/hooks` (husky, pre-commit, lefthook), which
#     is precisely the "fires destructively somewhere that isn't yours" failure. The commit
#     trailer therefore stays per-repo, installed by `tycho init` in that repo.
#   - **Trivially reversible.** `tycho uninstall --global` removes exactly what went in.


def _global_targets() -> list[Path]:
    home = claude_dir(Path.cwd(), GLOBAL)
    return [home / "settings.json", home / "commands"]


def _ask_global() -> bool:
    """Consent for a machine-wide install: name every path, then default to NO.

    Explicit rather than `[Y/n]` (the per-repo prompt's shape) because the blast radius is
    categorically different — this fires in repos the user didn't opt in, including ones
    that aren't theirs. A bare Enter must not install it.
    """
    print("tycho: this installs Tycho for EVERY repo on this machine. It will write:")
    for path in _global_targets():
        print(f"    {path}")
    print("  It only runs inside a git repo, defers to any per-repo install, and never")
    print("  touches your global git config. Undo at any time with `tycho uninstall --global`.")
    try:
        reply = input("tycho: install globally? [y/N] ")
    except EOFError:
        return False
    return reply.strip().lower() in ("y", "yes")


def init_global(assume_yes: bool = False, confirm=None) -> list[str]:
    """`tycho init --global` — wire Tycho into the user-level harness config, once, for good.

    Returns status lines. Installs nothing without an explicit yes: `assume_yes` is the
    scripted path (a user who typed `--global --yes` has already consented), `confirm`
    overrides the prompt for tests, and a run with neither and no TTY says how to proceed
    rather than guessing.
    """
    repo = Path.cwd()
    if not harness_mod.home("claude").is_dir():
        return ["tycho: Claude Code isn't installed for this user — nothing to wire globally."]
    ask = confirm or _ask_global
    if not assume_yes:
        if confirm is None and not sys.stdin.isatty():
            return ["tycho init --global needs a terminal to confirm — pass --yes to install "
                    "non-interactively"]
        if not ask():
            return ["tycho: global install skipped — nothing written."]
    try:
        lines = [_install_claude(repo, GLOBAL)]
    except ConfigRefused as exc:
        return [f"claude (global){REFUSED}{exc}"]
    lines.append("tycho: live in every git repo on this machine. It stays quiet outside git "
                 "repos and defers to any per-repo install.")
    lines.append("  The commit trailer is per-repo — run `tycho init` in a repo to add it.")
    lines.append("  Undo: `tycho uninstall --global`.")
    return lines


def uninstall_global() -> list[str]:
    """`tycho uninstall --global` — the exact inverse of `init_global`. Idempotent.

    Repo-local installs are deliberately *not* touched: they were separate, explicit
    decisions, and an uninstall that reached into every repo on the machine would be the
    same overreach in the other direction.
    """
    try:
        return [_uninstall_claude(Path.cwd(), GLOBAL)]
    except ConfigRefused as exc:
        return [f"claude (global){REFUSED}{exc}"]


def uninstall(repo: Path, only: str | None = None, purge: bool = False) -> list[str]:
    """Remove Tycho-owned hook entries; return status lines.

    Only ours come out — unrelated hooks, unrelated keys, and user-owned groups are
    left as they were. With ``only`` set (a harness name), touch just that harness.
    With ``purge`` set, also delete the repo-local `.tycho/` state and `.tycho.toml`
    config — an explicit opt-in, never the default, since it drops the catch trail.
    """
    removers = {
        "claude": _uninstall_claude,
        "cursor": _uninstall_cursor,
        "codex": _uninstall_codex,
        "opencode": _uninstall_opencode,
    }
    lines = []
    for name, fn in removers.items():
        if only and name != only:
            continue
        try:
            lines.append(fn(repo))
            # Forget what we recorded, or `doctor` would keep diagnosing a ghost. Only
            # after the config write succeeded — state must never claim less than truth.
            state.drop_install(repo, name)
        except ConfigRefused as exc:
            # Same rule as install: a config we can't parse is one we can't safely
            # rewrite. Removing our hook is not worth risking the rest of the file.
            lines.append(f"{name}{REFUSED}{exc}")
    # The commit-trailer hook is harness-agnostic — it's git's, not Claude's — so it comes
    # out on any uninstall of this repo, and stays silent when it was never there.
    try:
        lines += filter(None, [_uninstall_git_hook(repo), _uninstall_gitignore(repo)])
    except ConfigRefused as exc:
        lines.append(f"git{REFUSED}{exc}")
    if purge:
        lines += _purge_repo_local(repo)
    return lines


def _purge_repo_local(repo: Path) -> list[str]:
    """Delete the two repo-local artifacts Tycho owns whole: the `.tycho/` state dir
    (catch tally + evidence) and the `.tycho.toml` config. Idempotent — a missing target
    is a no-op line, not an error. Stays repo-local: the machine-wide state under
    `~/.local/share/tycho` (the all-time tally, shared across repos) is never touched.
    """
    lines = []
    for path in (state.dir_for(repo), config_mod.path(repo)):
        try:
            if path.is_dir():
                shutil.rmtree(path)
                lines.append(f"removed {path.name}/")
            elif path.exists():
                path.unlink()
                lines.append(f"removed {path.name}")
            else:
                lines.append(f"{path.name}: nothing to remove")
        except OSError as exc:
            # A delete we couldn't finish is an unfinished uninstall — mark it REFUSED so
            # the CLI exits non-zero, same contract as a config we couldn't rewrite.
            lines.append(f"{path.name}{REFUSED}{exc.strerror or exc}")
    return lines


def _current_text(path: Path) -> str | None:
    """What's on disk, or None if there's no file. Unreadable is refused, not ignored."""
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise ConfigRefused(f"cannot read {path} ({exc.strerror}) — fix the permissions and re-run") from exc


def _load(path: Path) -> dict:
    """Existing config as a dict. Missing or empty is {}; anything else we can't parse is refused.

    Refusing matters more than it looks: treating malformed JSON as `{}` and writing
    that back is how a verifier eats a developer's whole config. A hand-edit with a
    trailing comma is a file to leave alone, not a file to replace.
    """
    text = _current_text(path)
    if text is None or not text.strip():
        return {}
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ConfigRefused(
            f"{path} is not valid JSON (line {exc.lineno}: {exc.msg}) — fix or move it, then re-run"
        ) from exc
    if not isinstance(data, dict):
        raise ConfigRefused(f"{path} holds {type(data).__name__}, not a JSON object — leaving it alone")
    return data


def _write_text(path: Path, text: str, backup: bool = True) -> bool:
    """Write `text` to `path` atomically; return False if it was already correct.

    Resolves symlinks first: a settings file symlinked into a dotfiles repo must stay a
    symlink, so replace what it points at rather than the link itself. Writes to a
    sibling temp file and renames — rename is atomic, so a run killed mid-write leaves
    the original whole rather than a truncated husk. ``backup=False`` skips the `.bak` for
    files that are wholly ours and regenerable (a `/tycho` command), where a backup is
    just clutter — the settings file, which holds *user* data, always keeps one.
    """
    target = Path(os.path.realpath(path))
    current = _current_text(target)
    if current == text:
        return False  # already correct: no write, no backup, no mtime churn
    if current is not None and not os.access(target, os.W_OK):
        # A rename lands regardless of the *file's* mode, so without this the user's
        # deliberate chmod -w would be silently undone. (The dir's mode, and every
        # other way the filesystem can say no, is caught below.)
        raise ConfigRefused(f"{target} is read-only — chmod +w (or move it), then re-run")
    tmp = target.with_name(target.name + _TMP_SUFFIX)
    try:
        if current is not None and backup:
            # .bak holds the state immediately before this change, not a frozen
            # pristine original: it's the file you'd restore to undo what we just did.
            # Nothing is lost by overwriting it — we only ever get here for content
            # we're about to change, we refuse anything unparseable long before this,
            # and the user's own keys survive into every later copy regardless.
            shutil.copy2(target, target.with_name(target.name + _BACKUP_SUFFIX))
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp.write_text(text, encoding="utf-8")
        if current is not None:
            shutil.copymode(target, tmp)  # the user's permissions, not our umask's
        tmp.replace(target)
    except OSError as exc:
        # Anything the filesystem refuses — an unwritable parent dir, a full disk, a
        # quota — is a refusal like any other, not a traceback. The original is still
        # whole either way: nothing has replaced it yet.
        tmp.unlink(missing_ok=True)
        raise ConfigRefused(f"cannot write {target} ({exc.strerror}) — fix that, then re-run") from exc
    return True


def _write(path: Path, data: dict) -> bool:
    return _write_text(path, json.dumps(data, indent=2) + "\n")


def _status(label: str, what: str, path: Path, command: str, existed: bool, changed: bool) -> str:
    if not changed:
        return f"{label}: {what} already current → {path}"
    verb = "updated" if existed else "installed"
    return f"{label}: {verb} {what} → {path}  ({command})"


def _install_claude(repo: Path, scope: str = REPO) -> str:
    """Claude gets two things in the same file: the Stop hook, and (if free) the status bar.

    Both land in **one** write, which is not an optimisation. `.bak` must hold the state
    from before Tycho touched anything, so a second write would back up our own first one
    and destroy the copy the user would restore.

    `scope` picks the tree, and nothing else: the merge discipline, the backup, the refusal
    and the "only ours comes out" rule are identical for `~/.claude/settings.json` and the
    repo's. A global install differs only in the *command* (guarded — see `_GLOBAL_GUARD`),
    in leaving an existing user statusLine strictly alone, and in recording no per-repo
    install state, since there is no repo it belongs to.
    """
    # .claude/settings.json → hooks.Stop is a list of matcher-groups, each with a `hooks` list.
    path = settings_path(repo, scope)
    data = _load(path)
    command = _command_for_scope("hook", scope)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    groups, existed = _strip_claude_tycho(hooks.get("Stop") or [])
    groups.append({"hooks": [{"type": "command", "command": command}]})
    hooks["Stop"] = groups
    # SessionStart: surface a newer-version notice to the user at agent bootup.
    ss_command = _command_for_scope("session-start", scope)
    ss_groups, ss_existed = _strip_claude_tycho(hooks.get("SessionStart") or [])
    ss_groups.append({"hooks": [{"type": "command", "command": ss_command}]})
    hooks["SessionStart"] = ss_groups
    # UserPromptSubmit: mark a run in flight the moment a prompt is sent, so the badge turns
    # frost-blue "verifying" for the whole turn rather than only flickering at the Stop that
    # ends it. The Stop hook clears the pending beat to the verdict.
    ups_command = _command_for_scope("prompt-submit", scope)
    ups_groups, ups_existed = _strip_claude_tycho(hooks.get("UserPromptSubmit") or [])
    ups_groups.append({"hooks": [{"type": "command", "command": ups_command}]})
    hooks["UserPromptSubmit"] = ups_groups
    merged, statusline = _with_statusline(repo, {**data, "hooks": hooks}, path, scope)
    changed = _write(path, merged)
    if scope == REPO:
        state.write_install(repo, "claude", command)
    label = "claude" if scope == REPO else "claude (global)"
    hook_line = _status(label, "Stop hook", path, command, existed, changed)
    ss_line = _status(label, "SessionStart hook", path, ss_command, ss_existed, changed)
    ups_line = _status(label, "UserPromptSubmit hook", path, ups_command, ups_existed, changed)
    slash = _install_slash_commands(repo, scope)
    return "\n".join(filter(None, (hook_line, ss_line, ups_line, statusline, slash)))


# One flat file per subcommand (`.claude/commands/tycho-status.md` → `/tycho-status`) so
# each shows up with its own description in Claude Code's `/` autocomplete.
# `hide`/`show` are the discoverable face of the `tycho status --off/--on` toggle.
_SLASH_SUBCOMMANDS = {
    "status": ("Is Tycho live here, and its last verdict", "statusline"),
    "doctor": ("Full diagnostics: is Tycho installed, current, and firing?", "doctor"),
    "verify": ("Verify the latest session and render a verdict", "verify $ARGUMENTS"),
    "help": ("What Tycho is, whether it's live here, and every command", "help"),
    "count": ("How many problems Tycho has caught here, and all-time", "count"),
    "hide": ("Hide the Tycho status indicator (the hook keeps verifying)", "statusline --off"),
    "show": ("Show the Tycho status indicator again", "statusline --on"),
    "relay": ("Is the verdict relay on? (agent sees its verdict, works till VERIFIED)", "relay"),
    "relay-on": ("Turn ON the verdict relay — agent sees non-VERIFIED verdicts, works till VERIFIED (bounded)", "relay --on"),
    "relay-off": ("Turn OFF the verdict relay — verdicts stay human-only (the default)", "relay --off"),
    "override": ("Is the verdict override on? (agent may record per-check OVERRIDDEN, logged)", "override"),
    "override-on": ("Turn ON verdict override — agent may record a justified per-check OVERRIDDEN (logged)", "override --on"),
    "override-off": ("Turn OFF verdict override — the agent cannot override verdicts (the default)", "override --off"),
    "override-veto": ("Veto the agent's verdict override so the relay fires again (name a check, or bare for all)", "override --veto $ARGUMENTS"),
}


def _commands_dir(repo: Path, scope: str = REPO) -> Path:
    # Repo scope keeps its historical `<repo>/.claude/commands` (not `state.root_for`) —
    # `_install_claude` is always called with the repo root, and changing it would move
    # every already-installed command file.
    return (claude_dir(repo, GLOBAL) if scope == GLOBAL else repo / ".claude") / "commands"


def _q(s: str) -> str:
    """Quote a YAML frontmatter value. A bare colon-space in a description ("Full
    diagnostics: ...") reads as a nested mapping and breaks Claude Code's parse, which then
    falls back to showing the marker — so always quote, escaping `\\` and `"`."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _slash_body(description: str, cli_args: str, argument_hint: str = "") -> str:
    """A prompt-style command file backed by the real CLI.

    Prompt-style on purpose: relies only on the stable `.claude/commands/*.md` convention
    and `$ARGUMENTS`, not on `!`-exec / `allowed-tools` glob matching against a quoted
    interpreter path (the fiddly, version-sensitive part). Runs the exact command the
    terminal runs, so there's nothing extra to keep in sync.
    """
    # The YAML frontmatter MUST be the first thing in the file — Claude Code only parses it
    # when `---` is line 1, so the marker goes in the body, not above it (a marker on top
    # left the frontmatter unparsed and showed the comment itself as the description).
    hint = f"argument-hint: {_q(argument_hint)}\n" if argument_hint else ""
    return (
        "---\n"
        f"description: {_q(description)}\n{hint}"
        "---\n\n"
        f"{_SLASH_MARKER}\n\n"
        "Run this exact command with the Bash tool and show its output verbatim - "
        "nothing else, no commentary:\n\n"
        f"`{_command_for(cli_args)}`\n\n"
        "This is Tycho's own CLI (it also runs standalone in your terminal); it never edits code.\n"
    )


# The four scope commands. Each is its own `/tycho-scope-*` so it autocompletes
# with its own description and argument-hint. set/add/remove take path globs, which MUST be
# passed single-quoted so the shell doesn't expand them before Tycho stores them — the body
# says so explicitly. Value: (description, cli action, argument-hint).
_SCOPE_SLASH = {
    "scope-list": ("List the files/dirs the agent may edit (the scope_drift allowlist)", "list", ""),
    "scope-set": ("Replace the scope_drift allowlist with these path globs", "set", "<glob>… e.g. 'src/**' 'tests/**'"),
    "scope-add": ("Add path globs to the scope_drift allowlist", "add", "<glob>… e.g. 'src/**' 'tests/**'"),
    "scope-remove": ("Remove path globs from the scope_drift allowlist", "remove", "<glob>… e.g. 'tests/**'"),
}


def _scope_slash_body(description: str, action: str, argument_hint: str) -> str:
    """A `/tycho-scope-*` command file. `list` takes no args and reuses the generic body;
    set/add/remove instruct the agent to single-quote each glob so the shell keeps it
    literal (an un-quoted `src/**` would expand to files before Tycho ever sees it)."""
    if action == "list":
        return _slash_body(description, "scope list")
    cmd = _command_for(f"scope {action}")
    return (
        "---\n"
        f"description: {_q(description)}\n"
        f"argument-hint: {_q(argument_hint)}\n"
        "---\n\n"
        f"{_SLASH_MARKER}\n\n"
        "Update this repo's Tycho edit-scope, then show the command's output verbatim. Run it with "
        "the Bash tool, passing **each glob as a separate single-quoted argument** so the shell keeps "
        "it literal (an unquoted `src/**` expands to files before Tycho stores it):\n\n"
        f"`{cmd} '<glob>' '<glob>' …`\n\n"
        "The globs to use: $ARGUMENTS\n\n"
        "This edits `.tycho.toml` only — it never touches your code.\n"
    )


def _slash_files(repo: Path, scope: str = REPO) -> dict[Path, str]:
    """Path → body for every `/tycho` command file we install (flat `tycho-<sub>.md`)."""
    d = _commands_dir(repo, scope)
    files = {d / "tycho.md": _slash_body(
        "Run Tycho - verify what the agent claimed", "$ARGUMENTS",
        argument_hint="<status|doctor|verify|scope|help>",
    )}
    for name, (desc, args) in _SLASH_SUBCOMMANDS.items():
        files[d / f"tycho-{name}.md"] = _slash_body(desc, args)
    for name, (desc, action, hint) in _SCOPE_SLASH.items():
        files[d / f"tycho-{name}.md"] = _scope_slash_body(desc, action, hint)
    return files


def _install_slash_commands(repo: Path, scope: str = REPO) -> str | None:
    """Write the `/tycho` command set; skip any file the user wrote themselves.

    Same non-clobber rule as every other target: a command file without our marker is the
    user's, and stays put.
    """
    target = _slash_files(repo, scope)
    d = _commands_dir(repo, scope)
    # Remove any of *our* files from an earlier layout (the old `tycho/` namespace) that
    # aren't in the current set, plus any `.bak` clutter a previous write left behind — a
    # command file is wholly ours, so it never needed a backup.
    for path in [*_tycho_command_files(repo, scope), *d.glob("tycho*.tycho.bak")]:
        if path not in target and (path.suffix == ".bak" or _SLASH_MARKER in (_current_text(path) or "")):
            path.unlink()
    try:
        (d / "tycho").rmdir()  # tidy the old namespace dir if now empty
    except OSError:
        pass
    installed, skipped = [], []
    for path, body in target.items():
        existing = _current_text(path)
        if existing is not None and _SLASH_MARKER not in existing:
            skipped.append(path.name)
        elif _write_text(path, body, backup=False):
            installed.append(path)
    label = "claude" if scope == REPO else "claude (global)"
    lines = []
    if installed:
        lines.append(f"{label}: installed /tycho slash commands ({len(installed)}) → {d}")
    if skipped:
        lines.append(f"{label}: left your own command file(s) alone: {', '.join(sorted(set(skipped)))}")
    return "\n".join(lines) or None


def _user_statusline_command(repo: Path) -> str | None:
    """The command in the *user-level* Claude settings' statusLine, if any (read-only).

    We never write user-level config — but reading it tells us whether a repo-level
    statusLine of ours would *shadow* an existing one (a third-party badge lives here), and
    the repo slot wins. Knowing that lets Tycho compose with it instead of hiding it. Same
    read-only posture as harness detection: `$HOME` is a signal, never a write target.
    """
    try:
        data = json.loads((harness_mod.home("claude") / "settings.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    sl = data.get("statusLine") if isinstance(data, dict) else None
    cmd = sl.get("command") if isinstance(sl, dict) else None
    return cmd if isinstance(cmd, str) and not _is_tycho_status(cmd) else None


def _global_statusline(data: dict, path: Path) -> tuple[dict, str]:
    """The user-level status bar: take the slot only if it is empty, otherwise don't touch it.

    Repo scope can afford to *compose* with a foreign status line, because it owns the write
    and `tycho uninstall` in that repo puts the original back. Machine-wide there is no such
    symmetry — a user-level status line is the one a developer sees in every project, and
    quietly wrapping it everywhere is exactly the surprise `--global` must not spring. So:
    empty slot, we take it; occupied slot, we leave it and say so.
    """
    current = data.get("statusLine")
    if isinstance(current, dict) and not _is_tycho_status(current.get("command")):
        return data, ("claude (global): left your user-level statusLine alone — Tycho's badge "
                      "shows in repos where you run `tycho init`")
    base = current if isinstance(current, dict) else {}
    merged = {**base, "type": "command", "command": _command_for("statusline")}
    merged.setdefault("refreshInterval", _STATUS_REFRESH_MS)
    if merged == current:
        return data, ""
    return {**data, "statusLine": merged}, f"claude (global): installed statusLine → {path}"


def _with_statusline(repo: Path, data: dict, path: Path, scope: str = REPO) -> tuple[dict, str]:
    """Claim Claude Code's status bar, *composing* with any existing one.

    `statusLine` holds exactly one command, and a repo-level line wins over the user-level
    one — so Tycho could silently hide a working feature (a third-party badge, a shell prompt).
    It doesn't: instead of replacing, it becomes the slot and *runs the other command too*.
    - A foreign line in **this repo's** file is recorded (origin "repo") and restored on
      uninstall — we own the write, so we owe the restore.
    - A **user-level** line is recorded (origin "user") and left untouched; it resurfaces on
      its own once ours is removed. `tycho status` runs it and prepends its output.

    Shape verified against Claude Code 2.1.210: {"type": "command", "command": str}, plus
    optional padding/refreshInterval which are the user's to set — hence the merge.
    """
    if scope == GLOBAL:
        return _global_statusline(data, path)
    current = data.get("statusLine")
    command = status_command()
    ours = isinstance(current, dict) and _is_tycho_status(current.get("command"))
    foreign = current.get("command") if (isinstance(current, dict) and not ours) else None

    if isinstance(foreign, str):
        state.write_statusline_wrap(repo, foreign, origin="repo")
    elif (user_cmd := _user_statusline_command(repo)) is not None:
        state.write_statusline_wrap(repo, user_cmd, origin="user")
    else:
        state.clear_statusline_wrap(repo)

    base = current if (ours and isinstance(current, dict)) else {}  # keep our own extra keys only
    merged = {**base, "type": "command", "command": command}
    # Poll on top of the event-driven render. Claude Code renders the badge at the
    # Stop event, which fires while our hook is still verifying (entry beat = "pending"), so
    # without polling the badge sits on yellow until the *next* prompt instead of settling on
    # the verdict. A short interval re-renders it a beat later, once the verdict is written.
    # Left to the user if they've set their own (see the `base` merge above).
    merged.setdefault("refreshInterval", _STATUS_REFRESH_MS)
    if merged == current and state.read_statusline_wrap(repo) is None:
        return data, ""  # already ours, nothing to compose — the Stop-hook line speaks for it
    composing = " (composing with your existing status line)" if state.read_statusline_wrap(repo) else ""
    return {**data, "statusLine": merged}, f"claude: installed statusLine → {path}{composing}"


def _strip_claude_tycho(groups: list) -> tuple[list, bool]:
    """Drop any existing tycho hook entries (and now-empty groups); flag if any removed."""
    out, existed = [], False
    for group in groups:
        entries = (group.get("hooks") or []) if isinstance(group, dict) else []
        kept = [h for h in entries if not (isinstance(h, dict) and _is_tycho_owned(h.get("command")))]
        existed = existed or len(kept) != len(entries)
        if not isinstance(group, dict):
            out.append(group)
        elif kept or not entries:
            out.append({**group, "hooks": kept})
    return out, existed


def _install_cursor(repo: Path) -> str:
    # .cursor/hooks.json → hooks.stop is a flat list of {command, ...}; needs `version`.
    path = config_path(repo, "cursor")
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    command = hook_command()
    stop = list(hooks.get("stop") or [])
    kept = [h for h in stop if not (isinstance(h, dict) and _is_tycho_hook(h.get("command")))]
    existed = len(kept) != len(stop)
    kept.append({"command": command})
    hooks["stop"] = kept
    changed = _write(path, {**data, "version": data.get("version", 1), "hooks": hooks})
    state.write_install(repo, "cursor", command)
    return _status("cursor", "stop hook", path, command, existed, changed)


def _install_codex(repo: Path) -> str:
    """Codex shares Claude's hooks shape: `hooks.<Event>` is a list of matcher-groups. Stop
    drives the verdict; SessionStart surfaces the bootup update notice via `systemMessage`
    (Codex's output wire schema clones Claude's — docs/harness-support.md, ). Both go
    in one write so the .bak doesn't churn (same reason `_install_claude` batches its keys).
    """
    path = config_path(repo, "codex")
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    command = hook_command()
    groups, existed = _strip_claude_tycho(hooks.get("Stop") or [])
    groups.append({"hooks": [{"type": "command", "command": command}]})
    hooks["Stop"] = groups
    ss_command = _command_for("session-start")
    ss_groups, ss_existed = _strip_claude_tycho(hooks.get("SessionStart") or [])
    ss_groups.append({"hooks": [{"type": "command", "command": ss_command}]})
    hooks["SessionStart"] = ss_groups
    changed = _write(path, {**data, "hooks": hooks})
    state.write_install(repo, "codex", command)
    hook_line = _status("codex", "Stop hook", path, command, existed, changed)
    ss_line = _status("codex", "SessionStart hook", path, ss_command, ss_existed, changed)
    return "\n".join(filter(None, (hook_line, ss_line)))


def _install_opencode(repo: Path) -> str:
    # OpenCode has no Stop hook; a project plugin drives two Tycho entrypoints off the
    # plugin event bus, each handed the session id on stdin. Both toast their result via
    # client.tui.showToast — a genuinely user-facing sink:
    #   - session.idle  → `tycho hook`          (the Stop verdict, after every turn)
    #   - session.created → `tycho session-start` (the bootup update-notice, once per session)
    # Tycho rebuilds the transcript from opencode.db — no `opencode export` (which truncates
    # at 128 KB over a pipe).
    path = config_path(repo, "opencode")
    command = hook_argv(hook_command())
    notice = hook_argv(_command_for("session-start"))
    source = f'''{_PLUGIN_MARKER} OpenCode loads project plugins at startup.
const command = {json.dumps(command)}
const noticeCommand = {json.dumps(notice)}

export const TychoPlugin = async ({{ client, directory }}) => {{
  const run = async (argv, sessionID) => {{
    const proc = Bun.spawn([...argv], {{
      cwd: directory, stdin: "pipe", stdout: "pipe", stderr: "ignore",
    }})
    proc.stdin.write(JSON.stringify({{ harness: "opencode", sessionID, directory }}))
    proc.stdin.end()
    const text = (await new Response(proc.stdout).text()).trim()
    await proc.exited
    if (!text) return
    try {{
      const message = JSON.parse(text).message
      if (message) await client.tui.showToast({{
        body: {{ title: "Tycho", message, variant: "info" }},
      }})
    }} catch {{}}
  }}
  return {{
    event: async ({{ event }}) => {{
      if (event.type === "session.idle") {{
        const sessionID = event.properties?.sessionID
        if (sessionID) await run(command, sessionID)
      }} else if (event.type === "session.created") {{
        await run(noticeCommand, event.properties?.sessionID)
      }}
    }},
  }}
}}
'''
    # The whole file is ours, but a hand-written tycho.js is not — refuse rather than
    # overwrite someone else's plugin that happens to share our name.
    existed = path.exists()
    if existed and _PLUGIN_MARKER not in (_current_text(path) or ""):
        raise ConfigRefused(f"{path} wasn't generated by tycho init — move it aside, then re-run")
    changed = _write_text(path, source)
    state.write_install(repo, "opencode", shlex.join(command))
    return _status("opencode", "session.idle + session.created plugin", path, shlex.join(command), existed, changed)


# --- the git prepare-commit-msg hook (the commit trailer, strategy §6.6) -----


def git_hooks_dir(repo: Path) -> Path | None:
    """This repo's hooks directory, or None when `repo` isn't a git repo (or git is absent).

    `git rev-parse --git-path hooks` rather than `<repo>/.git/hooks`, because it is the only
    spelling that is right for all three shapes people actually have: a plain repo, a
    linked worktree or submodule (where `.git` is a *file*), and a repo that has moved its
    hooks with `core.hooksPath`. Getting that last one wrong would install a hook git never
    runs — the silently-dead-hook failure `doctor` exists to prevent.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--git-path", "hooks"],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
        )
    except (OSError, ValueError):
        return None  # no git on PATH — nothing to install into, and not an error
    if proc.returncode != 0 or not proc.stdout.strip():
        return None
    path = Path(proc.stdout.strip())
    # `--git-path` answers relative to the command's cwd, which `-C` set to `repo`.
    return path if path.is_absolute() else repo / path


def _git_hook_block() -> str:
    """Our fenced block: one line of work, wrapped so it cannot fail a commit.

    Three separate reasons this can't break `git commit`, because one isn't enough for
    something that runs on every commit a developer makes:

    - `|| :` swallows a non-zero exit (a deleted venv, a missing module, a broken install)
      even under `set -e`, which a user's own hook may well have set;
    - stdout and stderr are discarded, so a traceback can't corrupt the message file or
      spew into the commit flow;
    - the block never calls `exit`, so a *foreign* hook we were inserted into still runs
      every one of its own lines. That is also why we insert after the shebang rather than
      appending: a foreign hook that exits early would otherwise skip us silently.
    """
    return (
        f"{_GIT_BEGIN} — the Tycho-Attestation trailer. Remove with `tycho uninstall`.\n"
        f"# Fails open by construction: it can neither block nor fail this commit.\n"
        f'{attest_command()} "$1" "$2" >/dev/null 2>&1 || :\n'
        f"{_GIT_END}\n"
    )


def _make_executable(path: Path) -> None:
    """Git only runs a hook it can execute. No-op on Windows, where git goes by the shebang
    and `chmod` can't express the bit anyway."""
    try:
        mode = path.stat().st_mode
        path.chmod(mode | ((mode & 0o444) >> 2))  # +x wherever +r — i.e. `chmod +x` under umask
    except OSError:
        pass  # a hooks dir we can't chmod is a hook that won't fire — never a crash


def _install_git_hook(repo: Path) -> str | None:
    """Install/refresh the `prepare-commit-msg` hook. None when there's no repo to install into.

    Idempotent (our block is replaced in place, never stacked), polite (a hook that is
    already there keeps every line it had, and ours goes in right after its shebang), and
    refusing (a hook that isn't a `/bin/sh` script is left completely alone — we cannot
    reason about where a python or compiled hook would tolerate an inserted line).
    """
    hooks = git_hooks_dir(repo)
    if hooks is None:
        return None
    path = hooks / _GIT_HOOK
    current = _current_text(path)
    block = _git_hook_block()
    if current is None:
        text = f"#!/bin/sh\n{block}"
    elif _GIT_BLOCK_RE.search(current):
        text = _GIT_BLOCK_RE.sub(lambda _: block, current, count=1)
    elif not _SH_SHEBANG.match(current.splitlines()[0] if current.splitlines() else ""):
        raise ConfigRefused(
            f"{path} isn't a /bin/sh hook Tycho can extend safely — move it aside and re-run, "
            f"or add `{attest_command()} \"$1\" \"$2\" >/dev/null 2>&1 || :` to it yourself"
        )
    else:
        head, _, rest = current.partition("\n")
        text = f"{head}\n{block}{rest}"
    changed = _write_text(path, text, backup=current is not None)
    _make_executable(path)
    if not changed:
        return f"git: commit trailer hook already current → {path}"
    verb = "installed" if current is None else "added the Tycho block to your"
    return f"git: {verb} {_GIT_HOOK} hook → {path}"


# The line we add, and the comment that makes it ours to remove again. `.tycho/` is
# machine-local: a per-repo tally, the last-run heartbeat, and `turns.jsonl` — which carries
# the agent's own prose. None of it is shareable, all of it would dirty every `git status`,
# and the prose is the part you especially don't want arriving in someone else's PR.
_IGNORE_ENTRY = ".tycho/"
_IGNORE_NOTE = "# Tycho's machine-local state (tally, heartbeat, turn record)."
_IGNORE_BLOCK = f"{_IGNORE_NOTE}\n{_IGNORE_ENTRY}\n"


def _already_ignored(repo: Path) -> bool:
    """Is `.tycho/` already ignored here, by any means?

    Asks git rather than scanning `.gitignore`, because the entry can legitimately live in a
    parent `.gitignore`, in `.git/info/exclude`, or in the user's global excludesfile — and
    appending a duplicate to a repo that already ignores it is exactly the kind of unasked-for
    edit `init` is careful never to make. Any error reads as "not ignored"; the caller's write
    is idempotent anyway, so a false negative costs one comment line and never a wrong file.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "check-ignore", "-q", _IGNORE_ENTRY],
            capture_output=True,
        )
    except (OSError, ValueError):
        return False
    return proc.returncode == 0


def _install_gitignore(repo: Path) -> str | None:
    """Add `.tycho/` to the repo's `.gitignore`. None when there is nothing to do.

    Same discipline as every other file `init` touches: idempotent, appended rather than
    rewritten (every existing line survives, and ours goes at the end where an appended entry
    belongs), backed up before the change, and never the reason an install fails — a
    `.gitignore` we can't read or write is left completely alone.
    """
    if not gitstate.is_repo(repo) or _already_ignored(repo):
        return None
    path = repo / ".gitignore"
    current = _current_text(path)
    if current is not None and _IGNORE_ENTRY in current.splitlines():
        return None  # present but not effective (negated later, say) — not ours to fight
    if current is None:
        text = _IGNORE_BLOCK
    else:
        tail = "" if current.endswith("\n") else "\n"  # don't glue onto their last line
        text = f"{current}{tail}\n{_IGNORE_BLOCK}"     # blank line, then ours
    if not _write_text(path, text, backup=current is not None):
        return None
    return f"git: ignored {_IGNORE_ENTRY} → {path}"


def _uninstall_gitignore(repo: Path) -> str | None:
    """Take our two lines back out, leaving every other line exactly as it was."""
    path = repo / ".gitignore"
    current = _current_text(path)
    if not current or _IGNORE_BLOCK not in current:
        return None
    # Longest match first, so the blank separator line we added comes out with the block.
    # Removing the block but leaving its separator would mean `init; uninstall` never restores
    # the file byte-for-byte — which is the promise uninstall makes everywhere else.
    for pattern, replacement in ((f"\n\n{_IGNORE_BLOCK}", "\n"), (f"\n{_IGNORE_BLOCK}", "\n"),
                                 (_IGNORE_BLOCK, "")):
        if pattern in current:
            text = current.replace(pattern, replacement, 1)
            break
    else:
        return None
    if not text.strip():
        # Nothing survives but whitespace, so the file was ours — same rule as the commit
        # hook. Leaving an empty `.gitignore` we created is litter, not politeness.
        try:
            path.unlink()
        except OSError:
            return None
        return f"git: removed the {path.name} Tycho created → {path}"
    if not _write_text(path, text, backup=True):
        return None
    return f"git: stopped ignoring {_IGNORE_ENTRY} → {path}"


def _uninstall_git_hook(repo: Path) -> str | None:
    """Take our block back out. Restores the file byte-for-byte, or deletes it if it was ours.

    "Ours" means nothing survives removal but the shebang we wrote — anything else is a hook
    the user had (or wrote later) and stays, minus our fence.
    """
    hooks = git_hooks_dir(repo)
    if hooks is None:
        return None
    path = hooks / _GIT_HOOK
    current = _current_text(path)
    if current is None or not _GIT_BLOCK_RE.search(current):
        return None  # nothing of ours here — stay quiet rather than claim a removal
    remainder = _GIT_BLOCK_RE.sub("", current, count=1)
    if remainder.strip() in ("", "#!/bin/sh"):
        try:
            path.unlink()
            path.with_name(path.name + _BACKUP_SUFFIX).unlink(missing_ok=True)
        except OSError as exc:
            raise ConfigRefused(f"cannot remove {path} ({exc.strerror}) — fix that, then re-run") from exc
        return f"git: removed {_GIT_HOOK} hook → {path}"
    _write_text(path, remainder)
    return f"git: removed the Tycho block from {path}"


# --- uninstall ---------------------------------------------------------------
#
# We never delete a harness's config file: it may hold settings we didn't write
# (a `model`, unrelated hooks). We remove our entries, then drop a container only
# when it's empty *and* we were the ones who would have created it. The OpenCode
# plugin is the one exception — that whole file is ours, so it goes.


def _prune(data: dict, hooks: dict, key: str, kept: list) -> dict:
    """Put `kept` back under `key`, dropping containers we emptied."""
    if kept:
        hooks[key] = kept
    else:
        hooks.pop(key, None)  # init created this list; don't leave an empty one behind
    merged = {**data, "hooks": hooks}
    if not hooks:
        merged.pop("hooks", None)
    return merged


def _uninstall_claude(repo: Path, scope: str = REPO) -> str:
    """Take back the Stop hook and our statusLine — only ours, and in one write.

    Claude's file holds several Tycho-owned things (Stop, SessionStart, UserPromptSubmit,
    statusLine); removing them in separate writes would churn the backup for the same reason
    install batches them. Codex now batches its two keys the same way (`_uninstall_codex`).

    Scope-symmetric with `_install_claude` by construction: `_is_tycho_owned` matches a
    guarded global command exactly as it matches a bare repo-local one, so uninstall removes
    precisely what install wrote — the one invariant this module exists to hold.
    """
    label = "claude" if scope == REPO else "claude (global)"
    path = settings_path(repo, scope)
    if not path.exists():
        return f"{label}: nothing to remove (no config)"
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    groups, had_hook = _strip_claude_tycho(hooks.get("Stop") or [])
    ss_groups, had_ss = _strip_claude_tycho(hooks.get("SessionStart") or [])
    ups_groups, had_ups = _strip_claude_tycho(hooks.get("UserPromptSubmit") or [])
    current = data.get("statusLine")
    had_statusline = isinstance(current, dict) and _is_tycho_status(current.get("command"))
    slash = _uninstall_slash_commands(repo, scope)
    # A global install never wrote a compose record (it declines an occupied slot outright),
    # so there is none to read and none to clear — and clearing the *repo's* would be wrong.
    wrap = state.read_statusline_wrap(repo) if scope == REPO else None
    if scope == REPO:
        state.clear_statusline_wrap(repo)  # forget the compose target either way
    if not had_hook and not had_ss and not had_ups and not had_statusline:
        return slash or f"{label}: nothing to remove"
    _prune(data, hooks, "Stop", groups)  # mutates `hooks` in place…
    _prune(data, hooks, "SessionStart", ss_groups)  # …then the second key…
    merged = _prune(data, hooks, "UserPromptSubmit", ups_groups)  # …then the third
    restored = False
    if had_statusline:
        merged = {k: v for k, v in merged.items() if k != "statusLine"}
        # A foreign repo-level line we replaced is ours to put back; a user-level one
        # (origin "user", or no record) resurfaces on its own once ours is gone.
        if isinstance(wrap, dict) and wrap.get("origin") == "repo" and isinstance(wrap.get("command"), str):
            merged = {**merged, "statusLine": {"type": "command", "command": wrap["command"]}}
            restored = True
    _write(path, merged)
    lines = []
    if had_hook:
        lines.append(f"{label}: removed Stop hook → {path}")
    if had_ss:
        lines.append(f"{label}: removed SessionStart hook → {path}")
    if had_ups:
        lines.append(f"{label}: removed UserPromptSubmit hook → {path}")
    if had_statusline:
        lines.append(f"{label}: restored your statusLine → {path}" if restored
                     else f"{label}: removed statusLine → {path}")
    if slash:
        lines.append(slash)
    return "\n".join(lines)


def _tycho_command_files(repo: Path, scope: str = REPO) -> list[Path]:
    """Every command file that could be ours — the flat `tycho.md`/`tycho-*.md`, plus the
    old namespaced `tycho/*.md` from before the rename, so uninstall cleans both layouts."""
    d = _commands_dir(repo, scope)
    return [*d.glob("tycho.md"), *d.glob("tycho-*.md"), *(d / "tycho").glob("*.md")]


def _uninstall_slash_commands(repo: Path, scope: str = REPO) -> str | None:
    """Remove every `/tycho` command we generated; leave hand-written files alone."""
    d = _commands_dir(repo, scope)
    removed = False
    for path in _tycho_command_files(repo, scope):
        text = _current_text(path)
        if text is not None and _SLASH_MARKER in text:
            path.unlink()
            removed = True
    for tidy in (d / "tycho", d):
        try:
            tidy.rmdir()  # only if now empty — never take a dir holding someone's file
        except OSError:
            pass
    label = "claude" if scope == REPO else "claude (global)"
    return f"{label}: removed /tycho slash commands → {d}" if removed else None


def _uninstall_codex(repo: Path) -> str:
    """Remove the Stop and SessionStart hooks — only ours, in one write."""
    path = repo / ".codex" / "hooks.json"
    if not path.exists():
        return "codex: nothing to remove (no config)"
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    groups, had_hook = _strip_claude_tycho(hooks.get("Stop") or [])
    ss_groups, had_ss = _strip_claude_tycho(hooks.get("SessionStart") or [])
    if not had_hook and not had_ss:
        return "codex: nothing to remove"
    _prune(data, hooks, "Stop", groups)  # mutates `hooks` in place…
    merged = _prune(data, hooks, "SessionStart", ss_groups)  # …then the second key
    _write(path, merged)
    lines = []
    if had_hook:
        lines.append(f"codex: removed Stop hook → {path}")
    if had_ss:
        lines.append(f"codex: removed SessionStart hook → {path}")
    return "\n".join(lines)


def _uninstall_cursor(repo: Path) -> str:
    # .cursor/hooks.json → hooks.stop is a flat list of {command, ...}.
    path = repo / ".cursor" / "hooks.json"
    if not path.exists():
        return "cursor: nothing to remove (no config)"
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    stop = list(hooks.get("stop") or [])
    kept = [h for h in stop if not (isinstance(h, dict) and _is_tycho_hook(h.get("command")))]
    if len(kept) == len(stop):
        return "cursor: nothing to remove"
    _write(path, _prune(data, hooks, "stop", kept))
    return f"cursor: removed stop hook → {path}"


def _uninstall_opencode(repo: Path) -> str:
    # The whole plugin file is ours — but only if we generated it. A hand-written
    # tycho.js belongs to the user and is left alone.
    path = repo / ".opencode" / "plugins" / "tycho.js"
    if not path.exists():
        return "opencode: nothing to remove"
    try:
        generated = _PLUGIN_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        generated = False
    if not generated:
        return f"opencode: left {path} alone (not generated by tycho init)"
    path.unlink()
    try:
        path.parent.rmdir()  # tidy the plugins/ dir we made — only if now empty
    except OSError:
        pass  # user has other plugins, or the dir predates us: leave it
    return f"opencode: removed plugin → {path}"
