"""`tycho init` / `tycho uninstall` — manage the completion hook in each harness's config.

Writes are **repo-local** by default: only `<repo>/.claude`, `.cursor`, `.codex`,
`.opencode` and `<repo>/.git/hooks`. A harness's `$HOME` dir is *read* (never written) as a
detection signal. Two deliberate exceptions: the git `prepare-commit-msg` hook (still
repo-local, but runs inside `git commit`, so it fails open by construction), and `--global`
(`init_global`), which writes the user-level Claude config behind an explicit prompt.

Idempotent both ways. Install and uninstall share `_is_tycho_hook` + `_strip_claude_tycho`
so "which entry is ours" can't drift between them.

Every mutation is defensive because it runs against a real developer's real settings:
refuse what we can't parse rather than "recovering" it to `{}`, back up first, write
atomically, and skip the write when the file is already correct.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import shlex
from pathlib import Path

from . import config as config_mod
from . import gitstate
from . import harness as harness_mod
from . import opencode as opencode_mod
from . import state


# Proof a generated file is ours; uninstall deletes only files carrying the marker.
_PLUGIN_MARKER = "// Generated by tycho init."

# HTML comment so it renders invisibly when previewed as Markdown.
_SLASH_MARKER = "<!-- Generated by tycho init. -->"

# "We declined to touch this file" — the CLI matches on this constant for its exit code.
REFUSED = ": refused — "

_BACKUP_SUFFIX = ".tycho.bak"
_TMP_SUFFIX = ".tycho-tmp"

HARNESSES = ("claude", "cursor", "codex", "opencode")

# Install scopes: "repo" (default) or the user-level harness config (strategy §6.7).
REPO = "repo"
GLOBAL = "global"

# The git hook that stamps the `Tycho-Attestation:` trailer (strategy §6.6). Fenced by
# markers rather than owning the whole file — a repo may already have its own hook.
_GIT_HOOK = "prepare-commit-msg"
_GIT_BEGIN = "# >>> tycho"
_GIT_END = "# <<< tycho"
_GIT_BLOCK_RE = re.compile(rf"[ \t]*{re.escape(_GIT_BEGIN)}\b.*?{re.escape(_GIT_END)}[ \t]*\n?",
                           re.DOTALL)
# Hooks we'll append a `/bin/sh` block to. Anything else (python, a compiled binary, no
# shebang) is refused rather than rewritten.
_SH_SHEBANG = re.compile(r"^#!.*\b(sh|bash|dash|ash|zsh|ksh)\b")

# Per-repo config dir; created by the harness on first use, so its presence is a signal.
_LOCAL_DIR = {"claude": ".claude", "cursor": ".cursor", "codex": ".codex", "opencode": ".opencode"}

# Claude Code's `refreshInterval` is milliseconds.
# A user who sets their own value keeps it.
_STATUS_REFRESH_MS = 1000


class ConfigRefused(Exception):
    """This file must not be written — malformed, unreadable, or read-only. The message
    always carries the fix: whoever sees it is mid-install."""


def _quote_program(path: str) -> str:
    """Double-quote a program path containing a space — unquoted, a Windows path splits
    into two argv tokens under both cmd and /bin/sh."""
    return f'"{path}"' if " " in path and not path.startswith('"') else path


def hook_command() -> str:
    """A command the harness's plain `/bin/sh` can run. The Stop hook fires without an
    activated venv, so a bare ``tycho`` only works from a global/pipx install; otherwise
    resolve an absolute path, which runs regardless of PATH."""
    return _command_for("hook")


def status_command() -> str:
    """Same resolution as `hook_command`, for the status bar."""
    return _command_for("statusline")


def _command_for(subcommand: str) -> str:
    # Claude Code runs hook/statusLine commands through Git Bash, which eats unquoted
    # backslashes as escapes, so a native Windows path silently never fires. Emit forward
    # slashes via a blunt separator swap (not Path.as_posix, which is host-flavored).
    found = shutil.which("tycho")
    program = _quote_program((found or sys.executable).replace("\\", "/"))
    return f"{program} {subcommand}" if found else f"{program} -m tycho.cli {subcommand}"


def attest_command() -> str:
    """The command the git `prepare-commit-msg` hook runs to stamp the trailer. Module form
    because `attest.py` owns that entrypoint outright; absolute interpreter and forward
    slashes as in `hook_command` (git uses Git Bash on Windows too). A frozen build has no
    importable interpreter, so it uses the console-script form."""
    program = _quote_program(sys.executable.replace("\\", "/"))
    if getattr(sys, "frozen", False):
        return f"{program} attest --write"
    return f"{program} -m tycho.attest"


def hook_argv(command: str) -> list[str]:
    """Split a hook command into argv. ``posix=False`` so a ``C:\\...`` path keeps its
    backslashes (POSIX mode treats ``\\`` as an escape), then strip the quotes it leaves.
    An unbalanced quote yields ``[]``."""
    try:
        argv = shlex.split(command, posix=False)
    except ValueError:
        return []
    return [a.strip('"') for a in argv]


def _is_ours(command: object, subcommand: str) -> bool:
    """True if an existing entry is one of ours (any resolved form) — install and uninstall
    both route through this. Tolerant of the Windows ``tycho.exe`` suffix, surrounding
    quotes, and both path separators. Pure matching; no filesystem access."""
    if not isinstance(command, str) or not command.endswith(f" {subcommand}"):
        return False
    program = command[: -len(f" {subcommand}")].rstrip()
    if program.endswith("tycho.cli"):  # `<python> -m tycho.cli <subcommand>`
        return True
    base = re.split(r"[\\/]", program.strip('"'))[-1]  # basename, either separator
    return base.lower() in ("tycho", "tycho.exe")


def _is_tycho_hook(command: object) -> bool:
    return _is_ours(command, "hook")


def _is_tycho_status(command: object) -> bool:
    # `statusline` is canonical, `status` the old name: match both so init self-heals an
    # old statusLine and uninstall removes it either way.
    return _is_ours(command, "statusline") or _is_ours(command, "status")


def _is_tycho_session_start(command: object) -> bool:
    return _is_ours(command, "session-start")


def _is_tycho_prompt_submit(command: object) -> bool:
    return _is_ours(command, "prompt-submit")


def _is_tycho_owned(command: object) -> bool:
    """Any hook command Tycho installs into a matcher-group: Stop, SessionStart or
    UserPromptSubmit."""
    return (
        _is_tycho_hook(command)
        or _is_tycho_session_start(command)
        or _is_tycho_prompt_submit(command)
    )


def config_path(repo: Path, name: str) -> Path:
    """Where `name`'s repo-local config lives. Resolved from the same root as `.tycho/`, or
    `doctor` run from a subdirectory would find the root's install record but look for the
    harness config beside itself."""
    return state.root_for(repo) / {
        "claude": ".claude/settings.json",
        "cursor": ".cursor/hooks.json",
        "codex": ".codex/hooks.json",
        "opencode": ".opencode/plugins/tycho.js",
    }[name]


# The guard every *global* hook command carries. Two `exit 0`s: outside a git repo we do
# nothing (else a user-level hook would sprinkle `.tycho/` across the filesystem), and in a
# repo with its own Tycho hook we defer to it (anti-double-fire, checked at run time so it
# holds for repos wired before `--global` existed). Plain `/bin/sh` — no bashisms — because
# that's what Claude Code runs hook commands with (Git Bash on Windows). Every branch exits
# 0. ponytail: grepping for our own hook spelling is a cheap proxy for "the repo-local
# install owns this"; a false match only makes global stay quiet where repo-local is wired.
_GLOBAL_GUARD = (
    'git rev-parse --show-toplevel >/dev/null 2>&1 || exit 0; '
    'grep -qsE "tycho(\\.exe)? hook|tycho\\.cli hook" '
    '"$(git rev-parse --show-toplevel)/.claude/settings.json" && exit 0; '
)


def _command_for_scope(subcommand: str, scope: str) -> str:
    """The hook command for `subcommand`, guarded when going into the user-level config.
    Must still end in `" <subcommand>"` so `_is_ours` recognizes a guarded entry like a bare
    one. Routes Stop through `hook_command()`: that is the seam doctor's tests substitute,
    so it must stay the one source of the Stop command."""
    command = hook_command() if subcommand == "hook" else _command_for(subcommand)
    return _GLOBAL_GUARD + command if scope == GLOBAL else command


def claude_dir(repo: Path, scope: str = REPO) -> Path:
    """The `.claude` tree this scope writes into. Via `harness_mod.home`, the same function
    detection reads, so `CLAUDE_CONFIG_DIR` (or a test override) redirects both at once and
    the suite never touches a real `~/.claude`."""
    return harness_mod.home("claude") if scope == GLOBAL else state.root_for(repo) / ".claude"


def settings_path(repo: Path, scope: str = REPO) -> Path:
    return claude_dir(repo, scope) / "settings.json"


def global_installed() -> bool:
    """Is Tycho wired into the *user-level* Claude config right now? The config is the
    truth, not a marker we wrote: hand-removing the entry is uninstalling. Never raises —
    unparseable reads as "not installed", since we'd refuse to write it."""
    try:
        data = _load(settings_path(Path.cwd(), GLOBAL))
    except ConfigRefused:
        return False
    hooks = data.get("hooks") if isinstance(data.get("hooks"), dict) else {}
    return any(
        isinstance(entry, dict) and _is_tycho_owned(entry.get("command"))
        for group in (hooks.get("Stop") or [])
        if isinstance(group, dict)
        for entry in (group.get("hooks") or [])
    )


def installed_command(repo: Path, name: str) -> str | None:
    """The tycho hook command `name` would actually run, read back from its own config —
    what the harness will really execute, not what we meant to install. Raises
    ConfigRefused if the config can't be read."""
    path = config_path(repo, name)
    if name == "opencode":
        text = _current_text(path)
        if text is None or _PLUGIN_MARKER not in text:
            return None
        # The plugin holds its argv as a JSON array: `const command = ["...", "hook"]`.
        match = re.search(r"^const command = (\[.*\])$", text, re.MULTILINE)
        if not match:
            return None
        try:
            return shlex.join(json.loads(match.group(1)))
        except (json.JSONDecodeError, TypeError):
            return None
    data = _load(path)
    hooks = data.get("hooks") if isinstance(data.get("hooks"), dict) else {}
    if name == "cursor":
        entries = hooks.get("stop") or []
    else:
        entries = [h for g in (hooks.get("Stop") or []) if isinstance(g, dict) for h in (g.get("hooks") or [])]
    for entry in entries:
        if isinstance(entry, dict) and _is_tycho_hook(entry.get("command")):
            return entry["command"]
    return None


# --- detection ---------------------------------------------------------------
#
# Two cheap directory probes, either sufficient: the harness has run in this repo (dotdir)
# or is installed for the user (home). Never executed.


def detect(repo: Path) -> list[str]:
    """Enabled harnesses that appear to be present, in stable order. Gated to
    `harness_mod.ENABLED_NAMES` (Claude only for now): the other installers still exist and
    are tested, but init must not prompt to wire them up."""
    return [name for name in HARNESSES if name in harness_mod.ENABLED_NAMES and _is_present(name, repo)]


def _is_present(name: str, repo: Path) -> bool:
    if (repo / _LOCAL_DIR[name]).is_dir():
        return True
    if name == "opencode":
        # OpenCode's data lives in an XDG data dir, not a ~/.<name> dotdir.
        return opencode_mod.db_path().parent.is_dir()
    return harness_mod.home(name).is_dir()


def _ask(name: str) -> bool:
    """Prompt before touching one harness. Default yes; anything but n/no is yes."""
    try:
        reply = input(f"tycho: install the {name} completion hook in this repo? [Y/n] ")
    except EOFError:
        return False
    return reply.strip().lower() not in ("n", "no")


def init(
    repo: Path,
    only: str | None = None,
    assume_yes: bool = False,
    confirm=None,
    relay_confirm=None,
) -> list[str]:
    """Install the repo-local Stop hook per harness; return status lines. Asks before each
    one. ``only`` installs just that harness and skips detection — the user named it.
    ``assume_yes`` skips the prompts for scripted/CI installs."""
    installers = {
        "claude": _install_claude,
        "cursor": _install_cursor,
        "codex": _install_codex,
        "opencode": _install_opencode,
    }
    if only:
        names = [only]
    else:
        # A machine-wide install already covers this repo; installing again would give it
        # two Stop hooks per turn. Wire only the commit trailer, which global can't.
        if global_installed():
            return [
                "tycho: a global install is active — the Claude Code hooks already cover this "
                f"repo ({settings_path(repo, GLOBAL)}).",
                *_git_lines(repo),
                "  Per-repo anyway: `tycho init --harness claude` (global then defers to it).",
                "  Remove the global install: `tycho uninstall --global`.",
            ]
        names = detect(repo)
        if not names:
            return ["no supported harness detected here — pass --harness <name> to install anyway"]
    ask = confirm or _ask
    if not assume_yes and confirm is None and not sys.stdin.isatty():
        # Nobody's there to answer, and installing unasked is the thing to avoid.
        return [f"tycho init needs a terminal to confirm ({', '.join(names)}) — pass --yes to install non-interactively"]

    lines = []
    installed = []
    for name in names:
        if not assume_yes and not ask(name):
            lines.append(f"{name}: skipped")
            continue
        try:
            lines.append(installers[name](repo))
            installed.append(name)
        except ConfigRefused as exc:
            lines.append(f"{name}{REFUSED}{exc}")
    installed_any = bool(installed)
    # Read *before* `ensure` creates one, so the relay setup can tell "user configured
    # this" from "we just seeded it".
    config_existed = config_mod.path(repo).is_file()
    # Seed a .tycho.toml only once a harness got wired: a declined/refused install leaves
    # no config behind. Never clobbers an existing one.
    if installed_any and config_mod.ensure(repo):
        lines.append(
            f"created {config_mod.CONFIG_NAME} — no scope set yet, so nothing changes until you "
            f"run `tycho scope add '<glob>'`"
        )
    # Same rule as the config seed: no install means leave the user's repo alone.
    if installed_any:
        lines += _git_lines(repo)
    lines += _offer_relay(
        repo, any(name in installed for name in ("claude", "codex")),
        assume_yes, config_existed, relay_confirm,
    )
    return lines


def _git_lines(repo: Path) -> list[str]:
    """The commit-trailer hook and the `.tycho/` gitignore entry. Neither step may raise — a
    hook we won't touch is a reported outcome, not an aborted install — and the two are
    independent, so a refused hook still leaves the gitignore."""
    lines = []
    for step in (_install_git_hook, _install_gitignore):
        try:
            lines.append(step(repo))
        except ConfigRefused as exc:
            lines.append(f"git{REFUSED}{exc}")
    return [line for line in lines if line]


def _ask_relay() -> bool:
    """Prompt (default NO) to enable the verdict relay — it spends extra tokens, so only
    an explicit 'y'/'yes' enables it."""
    try:
        reply = input(
            "tycho: let the agent see its own verdict and keep working until VERIFIED? This feeds "
            "Tycho's verdict back into the agent (extra tokens; the loop is bounded). [y/N] "
        )
    except EOFError:
        return False
    return reply.strip().lower() in ("y", "yes")


def _offer_relay(
    repo: Path, relay_harness_installed: bool, assume_yes: bool,
    config_existed: bool, relay_confirm=None,
) -> list[str]:
    """Set up the verdict relay at install time (Claude and Codex). An existing `.tycho.toml`
    keeps its relay choice; otherwise ask (default NO). A scripted install (`--yes`, no TTY)
    never enables it silently. ``relay_confirm`` overrides the prompt for tests."""
    if not relay_harness_installed:
        return []
    if config_existed:
        state_txt = "ON" if state.relay_enabled(repo) else "OFF"
        return [
            f"tycho: verdict relay is {state_txt} (from your {config_mod.CONFIG_NAME}). Change it "
            f"with `tycho relay --on|--off`."
        ]
    interactive = relay_confirm is not None or (not assume_yes and sys.stdin.isatty())
    if not interactive:
        return []  # scripted / no TTY: leave the default (off), already written by config.ensure
    if (relay_confirm or _ask_relay)():
        state.set_relay_enabled(repo, True)
        return [
            f"tycho: verdict relay ON — the agent will see a non-VERIFIED verdict and keep working "
            f"until VERIFIED, up to {state.relay_max()} automatic re-checks per turn (extra tokens). "
            f"Turn it off with `tycho relay --off` or /tycho-relay-off."
        ]
    return [
        "tycho: verdict relay OFF (the default) — turn it on with `tycho relay --on` "
        "to have the agent work until VERIFIED."
    ]


def _wired_here(repo: Path, name: str) -> bool:
    """Does `name`'s config already carry our hook? A config we can't read counts as wired —
    we don't offer to overwrite something we can't inspect."""
    try:
        return installed_command(repo, name) is not None
    except ConfigRefused:
        return True


def _ask_setup(harnesses: list[str]) -> bool:
    reply = input(f"Set up Tycho in this repo ({', '.join(harnesses)})? [Y/n] ").strip().lower()
    return reply in ("", "y", "yes")


def offer_first_run(repo: Path, confirm=None) -> list[str]:
    """First-run nudge: a supported agent is here but Tycho isn't wired. Fires once per
    repo and never writes config without consent — the "already offered" marker lives
    outside the repo, and a decline touches nothing."""
    if state.already_offered(repo):
        return []
    detected = detect(repo)
    if not detected or state.read_install(repo) or any(_wired_here(repo, n) for n in detected):
        return []  # nothing here, or already set up
    state.mark_offered(repo)  # offered — regardless of the answer, don't ask again
    ask = confirm or _ask_setup
    interactive = confirm is not None or sys.stdin.isatty()  # a real TTY, or a test's confirm
    if interactive and ask(detected):
        return ["Tycho: setting up here…", *init(repo, only=None, assume_yes=True)]
    return [
        f"Tycho isn't set up in this repo yet — a supported agent ({', '.join(detected)}) is here.",
        "  Run `tycho init` to wire it up (offered once; it won't ask again).",
    ]


# --- the machine-wide install (strategy §6.7) --------------------------------
#
# `tycho init --global` writes the user-level Claude Code config once. Nothing below writes
# a `.tycho.toml` — zero-config must stay zero-config (`scope_drift` returns UNSUPPORTED
# with no config). Safety properties, since blast radius is the whole cost here: opt-in and
# loud (`_ask_global` names every path, defaults to NO); guarded at run time, not just
# install time (`_GLOBAL_GUARD`); additive only, leaving an existing user-level statusLine
# untouched (`_global_statusline`); and no `core.hooksPath`, which set machine-wide would
# silently disable every repo's own `.git/hooks` (husky, pre-commit, lefthook) — so the
# commit trailer stays per-repo.


def _global_targets() -> list[Path]:
    home = claude_dir(Path.cwd(), GLOBAL)
    return [home / "settings.json", home / "commands"]


def _ask_global() -> bool:
    """Consent for a machine-wide install: name every path, then default to NO. `[y/N]`, not
    the per-repo `[Y/n]` — this fires in repos the user never opted in, so a bare Enter must
    not install it."""
    print("tycho: this installs Tycho for EVERY repo on this machine. It will write:")
    for path in _global_targets():
        print(f"    {path}")
    print("  It only runs inside a git repo, defers to any per-repo install, and never")
    print("  touches your global git config. Undo at any time with `tycho uninstall --global`.")
    try:
        reply = input("tycho: install globally? [y/N] ")
    except EOFError:
        return False
    return reply.strip().lower() in ("y", "yes")


def init_global(assume_yes: bool = False, confirm=None) -> list[str]:
    """`tycho init --global` — wire Tycho into the user-level harness config. Installs
    nothing without an explicit yes; `assume_yes` is the scripted path, and neither that
    nor a TTY means we print how to proceed instead of guessing."""
    repo = Path.cwd()
    if not harness_mod.home("claude").is_dir():
        return ["tycho: Claude Code isn't installed for this user — nothing to wire globally."]
    ask = confirm or _ask_global
    if not assume_yes:
        if confirm is None and not sys.stdin.isatty():
            return ["tycho init --global needs a terminal to confirm — pass --yes to install "
                    "non-interactively"]
        if not ask():
            return ["tycho: global install skipped — nothing written."]
    try:
        lines = [_install_claude(repo, GLOBAL)]
    except ConfigRefused as exc:
        return [f"claude (global){REFUSED}{exc}"]
    lines.append("tycho: live in every git repo on this machine. It stays quiet outside git "
                 "repos and defers to any per-repo install.")
    lines.append("  The commit trailer is per-repo — run `tycho init` in a repo to add it.")
    lines.append("  Undo: `tycho uninstall --global`.")
    return lines


def uninstall_global() -> list[str]:
    """`tycho uninstall --global` — the exact inverse of `init_global`. Idempotent.
    Repo-local installs are deliberately not touched: separate, explicit decisions."""
    try:
        return [_uninstall_claude(Path.cwd(), GLOBAL)]
    except ConfigRefused as exc:
        return [f"claude (global){REFUSED}{exc}"]


def uninstall(repo: Path, only: str | None = None, purge: bool = False) -> list[str]:
    """Remove Tycho-owned hook entries; return status lines. Only ours come out — unrelated
    hooks, keys and user-owned groups stay. ``purge`` also deletes the repo-local `.tycho/`
    and `.tycho.toml`; never the default, since it drops the catch trail."""
    removers = {
        "claude": _uninstall_claude,
        "cursor": _uninstall_cursor,
        "codex": _uninstall_codex,
        "opencode": _uninstall_opencode,
    }
    lines = []
    for name, fn in removers.items():
        if only and name != only:
            continue
        try:
            lines.append(fn(repo))
            # Only after the config write succeeded, or `doctor` diagnoses a ghost.
            state.drop_install(repo, name)
        except ConfigRefused as exc:
            # Same rule as install: a config we can't parse is one we can't safely rewrite.
            lines.append(f"{name}{REFUSED}{exc}")
    # The commit-trailer hook is harness-agnostic, so it comes out on any uninstall here.
    try:
        lines += filter(None, [_uninstall_git_hook(repo), _uninstall_gitignore(repo)])
    except ConfigRefused as exc:
        lines.append(f"git{REFUSED}{exc}")
    if purge:
        lines += _purge_repo_local(repo)
    return lines


def _purge_repo_local(repo: Path) -> list[str]:
    """Delete the two repo-local artifacts Tycho owns whole: `.tycho/` and `.tycho.toml`.
    Idempotent. The machine-wide state under `~/.local/share/tycho` (the all-time tally,
    shared across repos) is never touched."""
    lines = []
    for path in (state.dir_for(repo), config_mod.path(repo)):
        try:
            if path.is_dir():
                shutil.rmtree(path)
                lines.append(f"removed {path.name}/")
            elif path.exists():
                path.unlink()
                lines.append(f"removed {path.name}")
            else:
                lines.append(f"{path.name}: nothing to remove")
        except OSError as exc:
            # An unfinished uninstall must exit non-zero, like a config we couldn't rewrite.
            lines.append(f"{path.name}{REFUSED}{exc.strerror or exc}")
    return lines


def _current_text(path: Path) -> str | None:
    """What's on disk, or None if there's no file. Unreadable is refused, not ignored."""
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise ConfigRefused(f"cannot read {path} ({exc.strerror}) — fix the permissions and re-run") from exc


def _load(path: Path) -> dict:
    """Existing config as a dict. Missing or empty is {}; unparseable is refused, because
    treating malformed JSON as `{}` and writing that back is how a verifier eats a
    developer's whole config."""
    text = _current_text(path)
    if text is None or not text.strip():
        return {}
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ConfigRefused(
            f"{path} is not valid JSON (line {exc.lineno}: {exc.msg}) — fix or move it, then re-run"
        ) from exc
    if not isinstance(data, dict):
        raise ConfigRefused(f"{path} holds {type(data).__name__}, not a JSON object — leaving it alone")
    return data


def _write_text(path: Path, text: str, backup: bool = True) -> bool:
    """Write `text` to `path` atomically; return False if it was already correct. Resolves
    symlinks first, so a settings file symlinked into a dotfiles repo stays a symlink. Temp
    file plus rename, so a run killed mid-write leaves the original whole. ``backup=False``
    only for files wholly ours; user data always keeps a `.bak`."""
    target = Path(os.path.realpath(path))
    current = _current_text(target)
    if current == text:
        return False  # already correct: no write, no backup, no mtime churn
    if current is not None and not os.access(target, os.W_OK):
        # A rename lands regardless of the *file's* mode, so without this a deliberate
        # `chmod -w` would be silently undone. Every other refusal is caught below.
        raise ConfigRefused(f"{target} is read-only — chmod +w (or move it), then re-run")
    tmp = target.with_name(target.name + _TMP_SUFFIX)
    try:
        if current is not None and backup:
            # .bak is the file you'd restore to undo *this* change, not a frozen pristine
            # original — so overwriting an older .bak is correct.
            shutil.copy2(target, target.with_name(target.name + _BACKUP_SUFFIX))
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp.write_text(text, encoding="utf-8")
        if current is not None:
            shutil.copymode(target, tmp)  # the user's permissions, not our umask's
        tmp.replace(target)
    except OSError as exc:
        # Any filesystem refusal (unwritable dir, full disk, quota) is a refusal, not a
        # traceback. The original is still whole — nothing has replaced it yet.
        tmp.unlink(missing_ok=True)
        raise ConfigRefused(f"cannot write {target} ({exc.strerror}) — fix that, then re-run") from exc
    return True


def _write(path: Path, data: dict) -> bool:
    return _write_text(path, json.dumps(data, indent=2) + "\n")


def _status(label: str, what: str, path: Path, command: str, existed: bool, changed: bool) -> str:
    if not changed:
        return f"{label}: {what} already current → {path}"
    verb = "updated" if existed else "installed"
    return f"{label}: {verb} {what} → {path}  ({command})"


def _install_claude(repo: Path, scope: str = REPO) -> str:
    """Claude gets the hooks and (if free) the status bar, in **one** write: a second write
    would back up our own first one and destroy the `.bak` the user would restore. `scope`
    picks the tree and nothing else — a global install differs only in the command (guarded,
    see `_GLOBAL_GUARD`), in leaving an existing user statusLine alone, and in recording no
    per-repo install state."""
    # .claude/settings.json → hooks.Stop is a list of matcher-groups, each with a `hooks` list.
    path = settings_path(repo, scope)
    data = _load(path)
    command = _command_for_scope("hook", scope)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    groups, existed = _strip_claude_tycho(hooks.get("Stop") or [])
    groups.append({"hooks": [{"type": "command", "command": command}]})
    hooks["Stop"] = groups
    # SessionStart: surface a newer-version notice to the user at agent bootup.
    ss_command = _command_for_scope("session-start", scope)
    ss_groups, ss_existed = _strip_claude_tycho(hooks.get("SessionStart") or [])
    ss_groups.append({"hooks": [{"type": "command", "command": ss_command}]})
    hooks["SessionStart"] = ss_groups
    # UserPromptSubmit: mark a run in flight at prompt time so the badge shows "verifying"
    # for the whole turn, not just a flicker at Stop. The Stop hook clears it to the verdict.
    ups_command = _command_for_scope("prompt-submit", scope)
    ups_groups, ups_existed = _strip_claude_tycho(hooks.get("UserPromptSubmit") or [])
    ups_groups.append({"hooks": [{"type": "command", "command": ups_command}]})
    hooks["UserPromptSubmit"] = ups_groups
    merged, statusline = _with_statusline(repo, {**data, "hooks": hooks}, path, scope)
    changed = _write(path, merged)
    if scope == REPO:
        state.write_install(repo, "claude", command)
    label = "claude" if scope == REPO else "claude (global)"
    hook_line = _status(label, "Stop hook", path, command, existed, changed)
    ss_line = _status(label, "SessionStart hook", path, ss_command, ss_existed, changed)
    ups_line = _status(label, "UserPromptSubmit hook", path, ups_command, ups_existed, changed)
    slash = _install_slash_commands(repo, scope)
    return "\n".join(filter(None, (hook_line, ss_line, ups_line, statusline, slash)))


# One flat file per subcommand (`.claude/commands/tycho-status.md` → `/tycho-status`) so
# each gets its own description in Claude Code's `/` autocomplete.
_SLASH_SUBCOMMANDS = {
    "status": ("Is Tycho live here, and its last verdict", "statusline"),
    "doctor": ("Full diagnostics: is Tycho installed, current, and firing?", "doctor"),
    "verify": ("Verify the latest session and render a verdict", "verify $ARGUMENTS"),
    "help": ("What Tycho is, whether it's live here, and every command", "help"),
    "count": ("How many problems Tycho has caught here, and all-time", "count"),
    "hide": ("Hide the Tycho status indicator (the hook keeps verifying)", "statusline --off"),
    "show": ("Show the Tycho status indicator again", "statusline --on"),
    "relay": ("Is the verdict relay on? (agent sees its verdict, works till VERIFIED)", "relay"),
    "relay-on": ("Turn ON the verdict relay — agent sees non-VERIFIED verdicts, works till VERIFIED (bounded)", "relay --on"),
    "relay-off": ("Turn OFF the verdict relay — verdicts stay human-only (the default)", "relay --off"),
    "override": ("Is the verdict override on? (agent may record per-check OVERRIDDEN, logged)", "override"),
    "override-on": ("Turn ON verdict override — agent may record a justified per-check OVERRIDDEN (logged)", "override --on"),
    "override-off": ("Turn OFF verdict override — the agent cannot override verdicts (the default)", "override --off"),
    "override-veto": ("Veto the agent's verdict override so the relay fires again (name a check, or bare for all)", "override --veto $ARGUMENTS"),
}


def _commands_dir(repo: Path, scope: str = REPO) -> Path:
    # Repo scope keeps `<repo>/.claude/commands` (not `state.root_for`); changing it would
    # move every already-installed command file.
    return (claude_dir(repo, GLOBAL) if scope == GLOBAL else repo / ".claude") / "commands"


def _q(s: str) -> str:
    """Quote a YAML frontmatter value. A bare colon-space in a description reads as a
    nested mapping and breaks Claude Code's parse, so always quote."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _slash_body(description: str, cli_args: str, argument_hint: str = "") -> str:
    """A prompt-style command file backed by the real CLI: relies only on the stable
    `.claude/commands/*.md` convention and `$ARGUMENTS`, not on `!`-exec / `allowed-tools`
    glob matching against a quoted interpreter path."""
    # The YAML frontmatter MUST start at line 1 or Claude Code won't parse it, so the
    # marker goes in the body, not above it.
    hint = f"argument-hint: {_q(argument_hint)}\n" if argument_hint else ""
    return (
        "---\n"
        f"description: {_q(description)}\n{hint}"
        "---\n\n"
        f"{_SLASH_MARKER}\n\n"
        "Run this exact command with the Bash tool and show its output verbatim - "
        "nothing else, no commentary:\n\n"
        f"`{_command_for(cli_args)}`\n\n"
        "This is Tycho's own CLI (it also runs standalone in your terminal); it never edits code.\n"
    )


# The scope commands: (description, cli action, argument-hint). set/add/remove take path
# globs, which MUST be single-quoted so the shell doesn't expand them before Tycho stores
# them — the body says so explicitly.
_SCOPE_SLASH = {
    "scope-list": ("List the files/dirs the agent may edit (the scope_drift allowlist)", "list", ""),
    "scope-set": ("Replace the scope_drift allowlist with these path globs", "set", "<glob>… e.g. 'src/**' 'tests/**'"),
    "scope-add": ("Add path globs to the scope_drift allowlist", "add", "<glob>… e.g. 'src/**' 'tests/**'"),
    "scope-remove": ("Remove path globs from the scope_drift allowlist", "remove", "<glob>… e.g. 'tests/**'"),
}


def _scope_slash_body(description: str, action: str, argument_hint: str) -> str:
    """A `/tycho-scope-*` command file. `list` reuses the generic body; set/add/remove tell
    the agent to single-quote each glob so the shell keeps it literal."""
    if action == "list":
        return _slash_body(description, "scope list")
    cmd = _command_for(f"scope {action}")
    return (
        "---\n"
        f"description: {_q(description)}\n"
        f"argument-hint: {_q(argument_hint)}\n"
        "---\n\n"
        f"{_SLASH_MARKER}\n\n"
        "Update this repo's Tycho edit-scope, then show the command's output verbatim. Run it with "
        "the Bash tool, passing **each glob as a separate single-quoted argument** so the shell keeps "
        "it literal (an unquoted `src/**` expands to files before Tycho stores it):\n\n"
        f"`{cmd} '<glob>' '<glob>' …`\n\n"
        "The globs to use: $ARGUMENTS\n\n"
        "This edits `.tycho.toml` only — it never touches your code.\n"
    )


def _slash_files(repo: Path, scope: str = REPO) -> dict[Path, str]:
    """Path → body for every `/tycho` command file we install (flat `tycho-<sub>.md`)."""
    d = _commands_dir(repo, scope)
    files = {d / "tycho.md": _slash_body(
        "Run Tycho - verify what the agent claimed", "$ARGUMENTS",
        argument_hint="<status|doctor|verify|scope|help>",
    )}
    for name, (desc, args) in _SLASH_SUBCOMMANDS.items():
        files[d / f"tycho-{name}.md"] = _slash_body(desc, args)
    for name, (desc, action, hint) in _SCOPE_SLASH.items():
        files[d / f"tycho-{name}.md"] = _scope_slash_body(desc, action, hint)
    return files


def _install_slash_commands(repo: Path, scope: str = REPO) -> str | None:
    """Write the `/tycho` command set. A command file without our marker is the user's and
    stays put."""
    target = _slash_files(repo, scope)
    d = _commands_dir(repo, scope)
    # Drop our files from the old `tycho/` namespace layout, plus `.bak` clutter — a
    # command file is wholly ours, so it never needed a backup.
    for path in [*_tycho_command_files(repo, scope), *d.glob("tycho*.tycho.bak")]:
        if path not in target and (path.suffix == ".bak" or _SLASH_MARKER in (_current_text(path) or "")):
            path.unlink()
    try:
        (d / "tycho").rmdir()  # tidy the old namespace dir if now empty
    except OSError:
        pass
    installed, skipped = [], []
    for path, body in target.items():
        existing = _current_text(path)
        if existing is not None and _SLASH_MARKER not in existing:
            skipped.append(path.name)
        elif _write_text(path, body, backup=False):
            installed.append(path)
    label = "claude" if scope == REPO else "claude (global)"
    lines = []
    if installed:
        lines.append(f"{label}: installed /tycho slash commands ({len(installed)}) → {d}")
    if skipped:
        lines.append(f"{label}: left your own command file(s) alone: {', '.join(sorted(set(skipped)))}")
    return "\n".join(lines) or None


def _user_statusline_command(repo: Path) -> str | None:
    """The command in the *user-level* Claude settings' statusLine, if any (read-only). The
    repo slot wins over the user-level one, so this tells us whether ours would shadow an
    existing badge. `$HOME` stays a signal, never a write target."""
    try:
        data = json.loads((harness_mod.home("claude") / "settings.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    sl = data.get("statusLine") if isinstance(data, dict) else None
    cmd = sl.get("command") if isinstance(sl, dict) else None
    return cmd if isinstance(cmd, str) and not _is_tycho_status(cmd) else None


def _global_statusline(data: dict, path: Path) -> tuple[dict, str]:
    """The user-level status bar: take the slot only if it is empty. Repo scope can compose
    with a foreign line because it owns the write and uninstall puts the original back;
    machine-wide there is no such symmetry, so an occupied slot is left alone."""
    current = data.get("statusLine")
    if isinstance(current, dict) and not _is_tycho_status(current.get("command")):
        return data, ("claude (global): left your user-level statusLine alone — Tycho's badge "
                      "shows in repos where you run `tycho init`")
    base = current if isinstance(current, dict) else {}
    merged = {**base, "type": "command", "command": _command_for("statusline")}
    merged.setdefault("refreshInterval", _STATUS_REFRESH_MS)
    if merged == current:
        return data, ""
    return {**data, "statusLine": merged}, f"claude (global): installed statusLine → {path}"


def _with_statusline(repo: Path, data: dict, path: Path, scope: str = REPO) -> tuple[dict, str]:
    """Claim Claude Code's status bar, *composing* with any existing one.

    `statusLine` holds one command and a repo-level line wins over the user-level one, so
    rather than hide a third-party badge we take the slot and run the other command too. A
    foreign line in this repo's file is recorded (origin "repo") and restored on uninstall;
    a user-level one (origin "user") is left untouched and resurfaces once ours is gone.
    Shape verified against Claude Code 2.1.210: {"type": "command", "command": str}, plus
    optional padding/refreshInterval which are the user's to set — hence the merge.
    """
    if scope == GLOBAL:
        return _global_statusline(data, path)
    current = data.get("statusLine")
    command = status_command()
    ours = isinstance(current, dict) and _is_tycho_status(current.get("command"))
    foreign = current.get("command") if (isinstance(current, dict) and not ours) else None

    if isinstance(foreign, str):
        state.write_statusline_wrap(repo, foreign, origin="repo")
    elif (user_cmd := _user_statusline_command(repo)) is not None:
        state.write_statusline_wrap(repo, user_cmd, origin="user")
    else:
        state.clear_statusline_wrap(repo)

    base = current if (ours and isinstance(current, dict)) else {}  # keep our own extra keys only
    merged = {**base, "type": "command", "command": command}
    # Claude Code renders the badge at the Stop event, which fires while our hook is still
    # verifying — without polling the badge sits on "pending" until the *next* prompt.
    merged.setdefault("refreshInterval", _STATUS_REFRESH_MS)
    if merged == current and state.read_statusline_wrap(repo) is None:
        return data, ""  # already ours, nothing to compose — the Stop-hook line speaks for it
    composing = " (composing with your existing status line)" if state.read_statusline_wrap(repo) else ""
    return {**data, "statusLine": merged}, f"claude: installed statusLine → {path}{composing}"


def _strip_claude_tycho(groups: list) -> tuple[list, bool]:
    """Drop any existing tycho hook entries (and now-empty groups); flag if any removed."""
    out, existed = [], False
    for group in groups:
        entries = (group.get("hooks") or []) if isinstance(group, dict) else []
        kept = [h for h in entries if not (isinstance(h, dict) and _is_tycho_owned(h.get("command")))]
        existed = existed or len(kept) != len(entries)
        if not isinstance(group, dict):
            out.append(group)
        elif kept or not entries:
            out.append({**group, "hooks": kept})
    return out, existed


def _install_cursor(repo: Path) -> str:
    # .cursor/hooks.json → hooks.stop is a flat list of {command, ...}; needs `version`.
    path = config_path(repo, "cursor")
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    command = hook_command()
    stop = list(hooks.get("stop") or [])
    kept = [h for h in stop if not (isinstance(h, dict) and _is_tycho_hook(h.get("command")))]
    existed = len(kept) != len(stop)
    kept.append({"command": command})
    hooks["stop"] = kept
    changed = _write(path, {**data, "version": data.get("version", 1), "hooks": hooks})
    state.write_install(repo, "cursor", command)
    return _status("cursor", "stop hook", path, command, existed, changed)


def _install_codex(repo: Path) -> str:
    """Codex shares Claude's hooks shape: `hooks.<Event>` is a list of matcher-groups, and
    its output wire schema clones Claude's. One write, so the
    .bak doesn't churn — same reason `_install_claude` batches its keys.
    """
    path = config_path(repo, "codex")
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    command = hook_command()
    groups, existed = _strip_claude_tycho(hooks.get("Stop") or [])
    groups.append({"hooks": [{"type": "command", "command": command}]})
    hooks["Stop"] = groups
    ss_command = _command_for("session-start")
    ss_groups, ss_existed = _strip_claude_tycho(hooks.get("SessionStart") or [])
    ss_groups.append({"hooks": [{"type": "command", "command": ss_command}]})
    hooks["SessionStart"] = ss_groups
    changed = _write(path, {**data, "hooks": hooks})
    state.write_install(repo, "codex", command)
    hook_line = _status("codex", "Stop hook", path, command, existed, changed)
    ss_line = _status("codex", "SessionStart hook", path, ss_command, ss_existed, changed)
    return "\n".join(filter(None, (hook_line, ss_line)))


def _install_opencode(repo: Path) -> str:
    # OpenCode has no Stop hook; a project plugin drives two entrypoints off the event bus,
    # each handed the session id on stdin, toasting via client.tui.showToast:
    #   - session.idle    → `tycho hook`          (the verdict, after every turn)
    #   - session.created → `tycho session-start` (the update notice, once per session)
    # The transcript comes from opencode.db, not `opencode export` (truncates at 128 KB
    # over a pipe).
    path = config_path(repo, "opencode")
    command = hook_argv(hook_command())
    notice = hook_argv(_command_for("session-start"))
    source = f'''{_PLUGIN_MARKER} OpenCode loads project plugins at startup.
const command = {json.dumps(command)}
const noticeCommand = {json.dumps(notice)}

export const TychoPlugin = async ({{ client, directory }}) => {{
  const run = async (argv, sessionID) => {{
    const proc = Bun.spawn([...argv], {{
      cwd: directory, stdin: "pipe", stdout: "pipe", stderr: "ignore",
    }})
    proc.stdin.write(JSON.stringify({{ harness: "opencode", sessionID, directory }}))
    proc.stdin.end()
    const text = (await new Response(proc.stdout).text()).trim()
    await proc.exited
    if (!text) return
    try {{
      const message = JSON.parse(text).message
      if (message) await client.tui.showToast({{
        body: {{ title: "Tycho", message, variant: "info" }},
      }})
    }} catch {{}}
  }}
  return {{
    event: async ({{ event }}) => {{
      if (event.type === "session.idle") {{
        const sessionID = event.properties?.sessionID
        if (sessionID) await run(command, sessionID)
      }} else if (event.type === "session.created") {{
        await run(noticeCommand, event.properties?.sessionID)
      }}
    }},
  }}
}}
'''
    # A hand-written tycho.js is not ours — refuse rather than overwrite it.
    existed = path.exists()
    if existed and _PLUGIN_MARKER not in (_current_text(path) or ""):
        raise ConfigRefused(f"{path} wasn't generated by tycho init — move it aside, then re-run")
    changed = _write_text(path, source)
    state.write_install(repo, "opencode", shlex.join(command))
    return _status("opencode", "session.idle + session.created plugin", path, shlex.join(command), existed, changed)


# --- the git prepare-commit-msg hook (the commit trailer, strategy §6.6) -----


def git_hooks_dir(repo: Path) -> Path | None:
    """This repo's hooks dir, or None when `repo` isn't a git repo (or git is absent). Uses
    `git rev-parse --git-path hooks`, not `<repo>/.git/hooks`: the only spelling correct for
    a plain repo, a linked worktree or submodule (`.git` is a *file*), and `core.hooksPath`.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--git-path", "hooks"],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
        )
    except (OSError, ValueError):
        return None  # no git on PATH — nothing to install into, and not an error
    if proc.returncode != 0 or not proc.stdout.strip():
        return None
    path = Path(proc.stdout.strip())
    # `--git-path` answers relative to the command's cwd, which `-C` set to `repo`.
    return path if path.is_absolute() else repo / path


def _git_hook_block() -> str:
    """Our fenced block: one line of work, wrapped so it cannot fail a commit. `|| :`
    swallows a non-zero exit even under a user's `set -e`; stdout/stderr are dropped so a
    traceback can't corrupt the message file; and the block never calls `exit`, so a foreign
    hook we sit in still runs every line. Inserted after the shebang rather than appended,
    since a foreign hook may exit early."""
    return (
        f"{_GIT_BEGIN} — the Tycho-Attestation trailer. Remove with `tycho uninstall`.\n"
        f"# Fails open by construction: it can neither block nor fail this commit.\n"
        f'{attest_command()} "$1" "$2" >/dev/null 2>&1 || :\n'
        f"{_GIT_END}\n"
    )


def _make_executable(path: Path) -> None:
    """Git only runs a hook it can execute. No-op on Windows, where git goes by the shebang
    and `chmod` can't express the bit anyway."""
    try:
        mode = path.stat().st_mode
        path.chmod(mode | ((mode & 0o444) >> 2))  # +x wherever +r — i.e. `chmod +x` under umask
    except OSError:
        pass  # a hooks dir we can't chmod is a hook that won't fire — never a crash


def _install_git_hook(repo: Path) -> str | None:
    """Install/refresh the `prepare-commit-msg` hook. None when there's no repo. Our block
    is replaced in place, never stacked; an existing hook keeps every line; and a hook that
    isn't a `/bin/sh` script is left alone, since we can't reason about where a python or
    compiled hook tolerates an inserted line."""
    hooks = git_hooks_dir(repo)
    if hooks is None:
        return None
    path = hooks / _GIT_HOOK
    current = _current_text(path)
    block = _git_hook_block()
    if current is None:
        text = f"#!/bin/sh\n{block}"
    elif _GIT_BLOCK_RE.search(current):
        text = _GIT_BLOCK_RE.sub(lambda _: block, current, count=1)
    elif not _SH_SHEBANG.match(current.splitlines()[0] if current.splitlines() else ""):
        raise ConfigRefused(
            f"{path} isn't a /bin/sh hook Tycho can extend safely — move it aside and re-run, "
            f"or add `{attest_command()} \"$1\" \"$2\" >/dev/null 2>&1 || :` to it yourself"
        )
    else:
        head, _, rest = current.partition("\n")
        text = f"{head}\n{block}{rest}"
    changed = _write_text(path, text, backup=current is not None)
    _make_executable(path)
    if not changed:
        return f"git: commit trailer hook already current → {path}"
    verb = "installed" if current is None else "added the Tycho block to your"
    return f"git: {verb} {_GIT_HOOK} hook → {path}"


# `.tycho/` is machine-local (tally, heartbeat, and `turns.jsonl`, which carries the
# agent's own prose). None of it is shareable or wanted in someone else's PR.
_IGNORE_ENTRY = ".tycho/"
_IGNORE_NOTE = "# Tycho's machine-local state (tally, heartbeat, turn record)."
_IGNORE_BLOCK = f"{_IGNORE_NOTE}\n{_IGNORE_ENTRY}\n"


def _already_ignored(repo: Path) -> bool:
    """Is `.tycho/` already ignored here, by any means? Asks git rather than scanning
    `.gitignore`: the entry can live in a parent `.gitignore`, `.git/info/exclude`, or the
    global excludesfile. Any error reads as "not ignored"."""
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "check-ignore", "-q", _IGNORE_ENTRY],
            capture_output=True,
        )
    except (OSError, ValueError):
        return False
    return proc.returncode == 0


def _install_gitignore(repo: Path) -> str | None:
    """Add `.tycho/` to the repo's `.gitignore`. None when there is nothing to do. Appended
    rather than rewritten, backed up first, and never the reason an install fails."""
    if not gitstate.is_repo(repo) or _already_ignored(repo):
        return None
    path = repo / ".gitignore"
    current = _current_text(path)
    if current is not None and _IGNORE_ENTRY in current.splitlines():
        return None  # present but not effective (negated later, say) — not ours to fight
    if current is None:
        text = _IGNORE_BLOCK
    else:
        tail = "" if current.endswith("\n") else "\n"  # don't glue onto their last line
        text = f"{current}{tail}\n{_IGNORE_BLOCK}"     # blank line, then ours
    if not _write_text(path, text, backup=current is not None):
        return None
    return f"git: ignored {_IGNORE_ENTRY} → {path}"


def _uninstall_gitignore(repo: Path) -> str | None:
    """Take our two lines back out, leaving every other line exactly as it was."""
    path = repo / ".gitignore"
    current = _current_text(path)
    if not current or _IGNORE_BLOCK not in current:
        return None
    # Longest match first, so the blank separator we added comes out with the block —
    # `init; uninstall` must restore the file byte-for-byte.
    for pattern, replacement in ((f"\n\n{_IGNORE_BLOCK}", "\n"), (f"\n{_IGNORE_BLOCK}", "\n"),
                                 (_IGNORE_BLOCK, "")):
        if pattern in current:
            text = current.replace(pattern, replacement, 1)
            break
    else:
        return None
    if not text.strip():
        # Nothing survives but whitespace, so the file was ours.
        try:
            path.unlink()
        except OSError:
            return None
        return f"git: removed the {path.name} Tycho created → {path}"
    if not _write_text(path, text, backup=True):
        return None
    return f"git: stopped ignoring {_IGNORE_ENTRY} → {path}"


def _uninstall_git_hook(repo: Path) -> str | None:
    """Take our block back out. Restores the file byte-for-byte, or deletes it if it was
    ours — "ours" meaning nothing survives removal but the shebang we wrote."""
    hooks = git_hooks_dir(repo)
    if hooks is None:
        return None
    path = hooks / _GIT_HOOK
    current = _current_text(path)
    if current is None or not _GIT_BLOCK_RE.search(current):
        return None  # nothing of ours here — stay quiet rather than claim a removal
    remainder = _GIT_BLOCK_RE.sub("", current, count=1)
    if remainder.strip() in ("", "#!/bin/sh"):
        try:
            path.unlink()
            path.with_name(path.name + _BACKUP_SUFFIX).unlink(missing_ok=True)
        except OSError as exc:
            raise ConfigRefused(f"cannot remove {path} ({exc.strerror}) — fix that, then re-run") from exc
        return f"git: removed {_GIT_HOOK} hook → {path}"
    _write_text(path, remainder)
    return f"git: removed the Tycho block from {path}"


# --- uninstall ---------------------------------------------------------------
#
# We never delete a harness's config file — it may hold settings we didn't write. Remove
# our entries, then drop a container only when it's empty *and* we would have created it.
# The OpenCode plugin is the exception: that whole file is ours, so it goes.


def _prune(data: dict, hooks: dict, key: str, kept: list) -> dict:
    """Put `kept` back under `key`, dropping containers we emptied."""
    if kept:
        hooks[key] = kept
    else:
        hooks.pop(key, None)  # init created this list; don't leave an empty one behind
    merged = {**data, "hooks": hooks}
    if not hooks:
        merged.pop("hooks", None)
    return merged


def _uninstall_claude(repo: Path, scope: str = REPO) -> str:
    """Take back our hooks and statusLine — only ours, in one write, or the backup churns
    (same reason install batches them). Scope-symmetric with `_install_claude`:
    `_is_tycho_owned` matches a guarded global command exactly as a bare repo-local one."""
    label = "claude" if scope == REPO else "claude (global)"
    path = settings_path(repo, scope)
    if not path.exists():
        return f"{label}: nothing to remove (no config)"
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    groups, had_hook = _strip_claude_tycho(hooks.get("Stop") or [])
    ss_groups, had_ss = _strip_claude_tycho(hooks.get("SessionStart") or [])
    ups_groups, had_ups = _strip_claude_tycho(hooks.get("UserPromptSubmit") or [])
    current = data.get("statusLine")
    had_statusline = isinstance(current, dict) and _is_tycho_status(current.get("command"))
    slash = _uninstall_slash_commands(repo, scope)
    # A global install never wrote a compose record, and clearing the *repo's* would be wrong.
    wrap = state.read_statusline_wrap(repo) if scope == REPO else None
    if scope == REPO:
        state.clear_statusline_wrap(repo)  # forget the compose target either way
    if not had_hook and not had_ss and not had_ups and not had_statusline:
        return slash or f"{label}: nothing to remove"
    _prune(data, hooks, "Stop", groups)  # mutates `hooks` in place…
    _prune(data, hooks, "SessionStart", ss_groups)  # …then the second key…
    merged = _prune(data, hooks, "UserPromptSubmit", ups_groups)  # …then the third
    restored = False
    if had_statusline:
        merged = {k: v for k, v in merged.items() if k != "statusLine"}
        # A foreign repo-level line we replaced is ours to put back; a user-level one
        # resurfaces on its own.
        if isinstance(wrap, dict) and wrap.get("origin") == "repo" and isinstance(wrap.get("command"), str):
            merged = {**merged, "statusLine": {"type": "command", "command": wrap["command"]}}
            restored = True
    _write(path, merged)
    lines = []
    if had_hook:
        lines.append(f"{label}: removed Stop hook → {path}")
    if had_ss:
        lines.append(f"{label}: removed SessionStart hook → {path}")
    if had_ups:
        lines.append(f"{label}: removed UserPromptSubmit hook → {path}")
    if had_statusline:
        lines.append(f"{label}: restored your statusLine → {path}" if restored
                     else f"{label}: removed statusLine → {path}")
    if slash:
        lines.append(slash)
    return "\n".join(lines)


def _tycho_command_files(repo: Path, scope: str = REPO) -> list[Path]:
    """Every command file that could be ours — the flat `tycho.md`/`tycho-*.md` plus the old
    namespaced `tycho/*.md`, so uninstall cleans both layouts."""
    d = _commands_dir(repo, scope)
    return [*d.glob("tycho.md"), *d.glob("tycho-*.md"), *(d / "tycho").glob("*.md")]


def _uninstall_slash_commands(repo: Path, scope: str = REPO) -> str | None:
    """Remove every `/tycho` command we generated; leave hand-written files alone."""
    d = _commands_dir(repo, scope)
    removed = False
    for path in _tycho_command_files(repo, scope):
        text = _current_text(path)
        if text is not None and _SLASH_MARKER in text:
            path.unlink()
            removed = True
    for tidy in (d / "tycho", d):
        try:
            tidy.rmdir()  # only if now empty — never take a dir holding someone's file
        except OSError:
            pass
    label = "claude" if scope == REPO else "claude (global)"
    return f"{label}: removed /tycho slash commands → {d}" if removed else None


def _uninstall_codex(repo: Path) -> str:
    """Remove the Stop and SessionStart hooks — only ours, in one write."""
    path = repo / ".codex" / "hooks.json"
    if not path.exists():
        return "codex: nothing to remove (no config)"
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    groups, had_hook = _strip_claude_tycho(hooks.get("Stop") or [])
    ss_groups, had_ss = _strip_claude_tycho(hooks.get("SessionStart") or [])
    if not had_hook and not had_ss:
        return "codex: nothing to remove"
    _prune(data, hooks, "Stop", groups)  # mutates `hooks` in place…
    merged = _prune(data, hooks, "SessionStart", ss_groups)  # …then the second key
    _write(path, merged)
    lines = []
    if had_hook:
        lines.append(f"codex: removed Stop hook → {path}")
    if had_ss:
        lines.append(f"codex: removed SessionStart hook → {path}")
    return "\n".join(lines)


def _uninstall_cursor(repo: Path) -> str:
    # .cursor/hooks.json → hooks.stop is a flat list of {command, ...}.
    path = repo / ".cursor" / "hooks.json"
    if not path.exists():
        return "cursor: nothing to remove (no config)"
    data = _load(path)
    hooks = dict(data.get("hooks") or {}) if isinstance(data.get("hooks"), dict) else {}
    stop = list(hooks.get("stop") or [])
    kept = [h for h in stop if not (isinstance(h, dict) and _is_tycho_hook(h.get("command")))]
    if len(kept) == len(stop):
        return "cursor: nothing to remove"
    _write(path, _prune(data, hooks, "stop", kept))
    return f"cursor: removed stop hook → {path}"


def _uninstall_opencode(repo: Path) -> str:
    # The whole plugin file is ours — but only if we generated it.
    path = repo / ".opencode" / "plugins" / "tycho.js"
    if not path.exists():
        return "opencode: nothing to remove"
    try:
        generated = _PLUGIN_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        generated = False
    if not generated:
        return f"opencode: left {path} alone (not generated by tycho init)"
    path.unlink()
    try:
        path.parent.rmdir()  # tidy the plugins/ dir we made — only if now empty
    except OSError:
        pass  # user has other plugins, or the dir predates us: leave it
    return f"opencode: removed plugin → {path}"
